# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EmployeeInfoEntry.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Employee(object):
    def setupUi(self, Employee):
        Employee.setObjectName(_fromUtf8("Employee"))
        Employee.resize(600, 650)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Employee.sizePolicy().hasHeightForWidth())
        Employee.setSizePolicy(sizePolicy)
        Employee.setMinimumSize(QtCore.QSize(600, 650))
        Employee.setMaximumSize(QtCore.QSize(600, 700))
        self.EmployeeListTable = QtGui.QTableWidget(Employee)
        self.EmployeeListTable.setGeometry(QtCore.QRect(19, 35, 201, 520))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EmployeeListTable.sizePolicy().hasHeightForWidth())
        self.EmployeeListTable.setSizePolicy(sizePolicy)
        self.EmployeeListTable.setMinimumSize(QtCore.QSize(201, 520))
        self.EmployeeListTable.setMaximumSize(QtCore.QSize(201, 500))
        self.EmployeeListTable.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.EmployeeListTable.setTabKeyNavigation(False)
        self.EmployeeListTable.setProperty("showDropIndicator", False)
        self.EmployeeListTable.setDragDropOverwriteMode(False)
        self.EmployeeListTable.setAlternatingRowColors(True)
        self.EmployeeListTable.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.EmployeeListTable.setColumnCount(1)
        self.EmployeeListTable.setObjectName(_fromUtf8("EmployeeListTable"))
        self.EmployeeListTable.setRowCount(0)
        self.EmployeeListTable.horizontalHeader().setVisible(False)
        self.EmployeeListTable.horizontalHeader().setStretchLastSection(True)
        self.EmployeeListTable.verticalHeader().setVisible(False)
        self.EmployeeListAddButt = QtGui.QPushButton(Employee)
        self.EmployeeListAddButt.setGeometry(QtCore.QRect(19, 560, 51, 27))
        self.EmployeeListAddButt.setObjectName(_fromUtf8("EmployeeListAddButt"))
        self.EmployeeListDelButt = QtGui.QPushButton(Employee)
        self.EmployeeListDelButt.setGeometry(QtCore.QRect(69, 560, 51, 27))
        self.EmployeeListDelButt.setObjectName(_fromUtf8("EmployeeListDelButt"))
        self.employeelabel = QtGui.QLabel(Employee)
        self.employeelabel.setGeometry(QtCore.QRect(20, 14, 81, 17))
        self.employeelabel.setObjectName(_fromUtf8("employeelabel"))
        self.tabWidget = QtGui.QTabWidget(Employee)
        self.tabWidget.setGeometry(QtCore.QRect(230, 10, 351, 581))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.PersonalInfoTAB = QtGui.QWidget()
        self.PersonalInfoTAB.setObjectName(_fromUtf8("PersonalInfoTAB"))
        self.empNameBox = QtGui.QLineEdit(self.PersonalInfoTAB)
        self.empNameBox.setGeometry(QtCore.QRect(11, 34, 241, 27))
        self.empNameBox.setObjectName(_fromUtf8("empNameBox"))
        self.doblabel = QtGui.QLabel(self.PersonalInfoTAB)
        self.doblabel.setGeometry(QtCore.QRect(14, 64, 241, 17))
        self.doblabel.setObjectName(_fromUtf8("doblabel"))
        self.empDepCombo = QtGui.QComboBox(self.PersonalInfoTAB)
        self.empDepCombo.setGeometry(QtCore.QRect(11, 134, 241, 33))
        self.empDepCombo.setObjectName(_fromUtf8("empDepCombo"))
        self.deplabel = QtGui.QLabel(self.PersonalInfoTAB)
        self.deplabel.setGeometry(QtCore.QRect(14, 114, 241, 17))
        self.deplabel.setObjectName(_fromUtf8("deplabel"))
        self.empnamelabel = QtGui.QLabel(self.PersonalInfoTAB)
        self.empnamelabel.setGeometry(QtCore.QRect(14, 14, 241, 17))
        self.empnamelabel.setObjectName(_fromUtf8("empnamelabel"))
        self.empDOBbox = QtGui.QDateEdit(self.PersonalInfoTAB)
        self.empDOBbox.setGeometry(QtCore.QRect(11, 84, 131, 27))
        self.empDOBbox.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.empDOBbox.setCalendarPopup(True)
        self.empDOBbox.setObjectName(_fromUtf8("empDOBbox"))
        self.homeBox = QtGui.QLineEdit(self.PersonalInfoTAB)
        self.homeBox.setGeometry(QtCore.QRect(10, 351, 241, 27))
        self.homeBox.setObjectName(_fromUtf8("homeBox"))
        self.mobilelabel = QtGui.QLabel(self.PersonalInfoTAB)
        self.mobilelabel.setGeometry(QtCore.QRect(13, 281, 241, 17))
        self.mobilelabel.setObjectName(_fromUtf8("mobilelabel"))
        self.phonelabel = QtGui.QLabel(self.PersonalInfoTAB)
        self.phonelabel.setGeometry(QtCore.QRect(13, 331, 241, 17))
        self.phonelabel.setObjectName(_fromUtf8("phonelabel"))
        self.emailBox = QtGui.QLineEdit(self.PersonalInfoTAB)
        self.emailBox.setGeometry(QtCore.QRect(10, 251, 241, 27))
        self.emailBox.setObjectName(_fromUtf8("emailBox"))
        self.emaillabel = QtGui.QLabel(self.PersonalInfoTAB)
        self.emaillabel.setGeometry(QtCore.QRect(13, 231, 241, 17))
        self.emaillabel.setObjectName(_fromUtf8("emaillabel"))
        self.mobileBox = QtGui.QLineEdit(self.PersonalInfoTAB)
        self.mobileBox.setGeometry(QtCore.QRect(10, 301, 241, 27))
        self.mobileBox.setObjectName(_fromUtf8("mobileBox"))
        self.empAgeBox = QtGui.QSpinBox(self.PersonalInfoTAB)
        self.empAgeBox.setGeometry(QtCore.QRect(174, 84, 48, 27))
        self.empAgeBox.setReadOnly(True)
        self.empAgeBox.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.empAgeBox.setObjectName(_fromUtf8("empAgeBox"))
        self.aglabel = QtGui.QLabel(self.PersonalInfoTAB)
        self.aglabel.setGeometry(QtCore.QRect(175, 64, 56, 17))
        self.aglabel.setObjectName(_fromUtf8("aglabel"))
        self.adrsBox = QtGui.QTextEdit(self.PersonalInfoTAB)
        self.adrsBox.setGeometry(QtCore.QRect(10, 402, 241, 81))
        self.adrsBox.setObjectName(_fromUtf8("adrsBox"))
        self.adrslabel = QtGui.QLabel(self.PersonalInfoTAB)
        self.adrslabel.setGeometry(QtCore.QRect(10, 382, 241, 17))
        self.adrslabel.setObjectName(_fromUtf8("adrslabel"))
        self.empStDateBox = QtGui.QDateEdit(self.PersonalInfoTAB)
        self.empStDateBox.setGeometry(QtCore.QRect(11, 510, 111, 27))
        self.empStDateBox.setCalendarPopup(True)
        self.empStDateBox.setObjectName(_fromUtf8("empStDateBox"))
        self.stdatelabel = QtGui.QLabel(self.PersonalInfoTAB)
        self.stdatelabel.setGeometry(QtCore.QRect(14, 490, 61, 17))
        self.stdatelabel.setObjectName(_fromUtf8("stdatelabel"))
        self.empSalCombo = QtGui.QComboBox(self.PersonalInfoTAB)
        self.empSalCombo.setGeometry(QtCore.QRect(11, 190, 140, 31))
        self.empSalCombo.setObjectName(_fromUtf8("empSalCombo"))
        self.label = QtGui.QLabel(self.PersonalInfoTAB)
        self.label.setGeometry(QtCore.QRect(14, 173, 100, 17))
        self.label.setObjectName(_fromUtf8("label"))
        self.EmployeeListSaveButt = QtGui.QPushButton(self.PersonalInfoTAB)
        self.EmployeeListSaveButt.setGeometry(QtCore.QRect(128, 510, 61, 27))
        self.EmployeeListSaveButt.setObjectName(_fromUtf8("EmployeeListSaveButt"))
        self.EmployeeListSaveCancelButt = QtGui.QPushButton(self.PersonalInfoTAB)
        self.EmployeeListSaveCancelButt.setGeometry(QtCore.QRect(190, 510, 61, 27))
        self.EmployeeListSaveCancelButt.setObjectName(_fromUtf8("EmployeeListSaveCancelButt"))
        self.tabWidget.addTab(self.PersonalInfoTAB, _fromUtf8(""))
        self.payrollInformationTab = QtGui.QWidget()
        self.payrollInformationTab.setObjectName(_fromUtf8("payrollInformationTab"))
        self.sallabel = QtGui.QLabel(self.payrollInformationTab)
        self.sallabel.setGeometry(QtCore.QRect(10, 7, 241, 17))
        self.sallabel.setObjectName(_fromUtf8("sallabel"))
        self.SalaryAddButt = QtGui.QPushButton(self.payrollInformationTab)
        self.SalaryAddButt.setGeometry(QtCore.QRect(10, 200, 51, 27))
        self.SalaryAddButt.setObjectName(_fromUtf8("SalaryAddButt"))
        self.salaryTable = QtGui.QTableWidget(self.payrollInformationTab)
        self.salaryTable.setGeometry(QtCore.QRect(10, 27, 311, 171))
        self.salaryTable.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.salaryTable.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.salaryTable.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerItem)
        self.salaryTable.setColumnCount(4)
        self.salaryTable.setObjectName(_fromUtf8("salaryTable"))
        self.salaryTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.salaryTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.salaryTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.salaryTable.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.salaryTable.setHorizontalHeaderItem(3, item)
        self.salaryTable.horizontalHeader().setDefaultSectionSize(50)
        self.salaryTable.horizontalHeader().setMinimumSectionSize(20)
        self.salaryTable.horizontalHeader().setStretchLastSection(False)
        self.salaryTable.verticalHeader().setVisible(False)
        self.bonuslabel = QtGui.QLabel(self.payrollInformationTab)
        self.bonuslabel.setGeometry(QtCore.QRect(10, 247, 241, 17))
        self.bonuslabel.setObjectName(_fromUtf8("bonuslabel"))
        self.BonusAddButt = QtGui.QPushButton(self.payrollInformationTab)
        self.BonusAddButt.setGeometry(QtCore.QRect(10, 440, 51, 30))
        self.BonusAddButt.setObjectName(_fromUtf8("BonusAddButt"))
        self.bonusTable = QtGui.QTableWidget(self.payrollInformationTab)
        self.bonusTable.setGeometry(QtCore.QRect(10, 267, 311, 171))
        self.bonusTable.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.bonusTable.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.bonusTable.setObjectName(_fromUtf8("bonusTable"))
        self.bonusTable.setColumnCount(4)
        self.bonusTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.bonusTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.bonusTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.bonusTable.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.bonusTable.setHorizontalHeaderItem(3, item)
        self.bonusTable.horizontalHeader().setDefaultSectionSize(50)
        self.bonusTable.horizontalHeader().setMinimumSectionSize(20)
        self.bonusTable.horizontalHeader().setStretchLastSection(False)
        self.bonusTable.verticalHeader().setVisible(False)
        self.SalaryDelButt = QtGui.QPushButton(self.payrollInformationTab)
        self.SalaryDelButt.setGeometry(QtCore.QRect(60, 200, 51, 27))
        self.SalaryDelButt.setObjectName(_fromUtf8("SalaryDelButt"))
        self.BonusDelButt = QtGui.QPushButton(self.payrollInformationTab)
        self.BonusDelButt.setGeometry(QtCore.QRect(60, 440, 51, 30))
        self.BonusDelButt.setObjectName(_fromUtf8("BonusDelButt"))
        self.finishlabel = QtGui.QLabel(self.payrollInformationTab)
        self.finishlabel.setGeometry(QtCore.QRect(12, 490, 71, 17))
        self.finishlabel.setObjectName(_fromUtf8("finishlabel"))
        self.finishDateBox = QtGui.QDateEdit(self.payrollInformationTab)
        self.finishDateBox.setGeometry(QtCore.QRect(10, 510, 111, 27))
        self.finishDateBox.setCalendarPopup(True)
        self.finishDateBox.setObjectName(_fromUtf8("finishDateBox"))
        self.finishDateUpdateBUT = QtGui.QPushButton(self.payrollInformationTab)
        self.finishDateUpdateBUT.setGeometry(QtCore.QRect(130, 510, 61, 27))
        self.finishDateUpdateBUT.setObjectName(_fromUtf8("finishDateUpdateBUT"))
        self.BonusUpdateBUT = QtGui.QPushButton(self.payrollInformationTab)
        self.BonusUpdateBUT.setGeometry(QtCore.QRect(237, 440, 85, 27))
        self.BonusUpdateBUT.setObjectName(_fromUtf8("BonusUpdateBUT"))
        self.SalaryUpdateBUT = QtGui.QPushButton(self.payrollInformationTab)
        self.SalaryUpdateBUT.setGeometry(QtCore.QRect(238, 200, 85, 27))
        self.SalaryUpdateBUT.setObjectName(_fromUtf8("SalaryUpdateBUT"))
        self.tabWidget.addTab(self.payrollInformationTab, _fromUtf8(""))
        self.HolidayTab = QtGui.QWidget()
        self.HolidayTab.setObjectName(_fromUtf8("HolidayTab"))
        self.holidayEntitlementTable = QtGui.QTableWidget(self.HolidayTab)
        self.holidayEntitlementTable.setGeometry(QtCore.QRect(10, 36, 311, 190))
        self.holidayEntitlementTable.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.holidayEntitlementTable.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.holidayEntitlementTable.setObjectName(_fromUtf8("holidayEntitlementTable"))
        self.holidayEntitlementTable.setColumnCount(3)
        self.holidayEntitlementTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.holidayEntitlementTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.holidayEntitlementTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.holidayEntitlementTable.setHorizontalHeaderItem(2, item)
        self.holidayEntitlementTable.horizontalHeader().setDefaultSectionSize(50)
        self.holidayEntitlementTable.horizontalHeader().setMinimumSectionSize(20)
        self.holidayEntitlementTable.horizontalHeader().setStretchLastSection(False)
        self.holidayEntitlementTable.verticalHeader().setVisible(False)
        self.holidaylabel = QtGui.QLabel(self.HolidayTab)
        self.holidaylabel.setGeometry(QtCore.QRect(10, 16, 241, 17))
        self.holidaylabel.setObjectName(_fromUtf8("holidaylabel"))
        self.holidayEntitlementAddBUT = QtGui.QPushButton(self.HolidayTab)
        self.holidayEntitlementAddBUT.setGeometry(QtCore.QRect(10, 230, 51, 27))
        self.holidayEntitlementAddBUT.setObjectName(_fromUtf8("holidayEntitlementAddBUT"))
        self.holidayEntitlementDelBUT = QtGui.QPushButton(self.HolidayTab)
        self.holidayEntitlementDelBUT.setGeometry(QtCore.QRect(60, 230, 51, 27))
        self.holidayEntitlementDelBUT.setObjectName(_fromUtf8("holidayEntitlementDelBUT"))
        self.HolidayUpdateBUT = QtGui.QPushButton(self.HolidayTab)
        self.HolidayUpdateBUT.setGeometry(QtCore.QRect(238, 230, 85, 27))
        self.HolidayUpdateBUT.setObjectName(_fromUtf8("HolidayUpdateBUT"))
        self.tabWidget.addTab(self.HolidayTab, _fromUtf8(""))
        self.UpdateEmpRecordBUT = QtGui.QPushButton(Employee)
        self.UpdateEmpRecordBUT.setGeometry(QtCore.QRect(460, 610, 121, 27))
        self.UpdateEmpRecordBUT.setObjectName(_fromUtf8("UpdateEmpRecordBUT"))
        self.closeEmployeePopUpBUT = QtGui.QPushButton(Employee)
        self.closeEmployeePopUpBUT.setGeometry(QtCore.QRect(336, 610, 121, 27))
        self.closeEmployeePopUpBUT.setObjectName(_fromUtf8("closeEmployeePopUpBUT"))

        self.retranslateUi(Employee)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Employee)

    def retranslateUi(self, Employee):
        Employee.setWindowTitle(_translate("Employee", "Employee Information", None))
        self.EmployeeListAddButt.setText(_translate("Employee", "Add", None))
        self.EmployeeListDelButt.setText(_translate("Employee", "Delete", None))
        self.employeelabel.setText(_translate("Employee", "Employee", None))
        self.doblabel.setText(_translate("Employee", "Date of Birth", None))
        self.deplabel.setText(_translate("Employee", "Department", None))
        self.empnamelabel.setText(_translate("Employee", "Employee Name", None))
        self.mobilelabel.setText(_translate("Employee", "Mobile", None))
        self.phonelabel.setText(_translate("Employee", "Home Phone", None))
        self.emaillabel.setText(_translate("Employee", "Email", None))
        self.aglabel.setText(_translate("Employee", "Age", None))
        self.adrslabel.setText(_translate("Employee", "Address", None))
        self.stdatelabel.setText(_translate("Employee", "Start Date", None))
        self.label.setText(_translate("Employee", "Salary or Hourly", None))
        self.EmployeeListSaveButt.setText(_translate("Employee", "Save", None))
        self.EmployeeListSaveCancelButt.setText(_translate("Employee", "Cancel", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.PersonalInfoTAB), _translate("Employee", "Personal Details", None))
        self.sallabel.setText(_translate("Employee", "Salary", None))
        self.SalaryAddButt.setText(_translate("Employee", "Add", None))
        item = self.salaryTable.horizontalHeaderItem(0)
        item.setText(_translate("Employee", "ID", None))
        item = self.salaryTable.horizontalHeaderItem(1)
        item.setText(_translate("Employee", "Salary", None))
        item = self.salaryTable.horizontalHeaderItem(2)
        item.setText(_translate("Employee", "Hourly", None))
        item = self.salaryTable.horizontalHeaderItem(3)
        item.setText(_translate("Employee", "Adjust Date", None))
        self.bonuslabel.setText(_translate("Employee", "Bonus Information", None))
        self.BonusAddButt.setText(_translate("Employee", "Add", None))
        item = self.bonusTable.horizontalHeaderItem(0)
        item.setText(_translate("Employee", "ID", None))
        item = self.bonusTable.horizontalHeaderItem(1)
        item.setText(_translate("Employee", "Bonus", None))
        item = self.bonusTable.horizontalHeaderItem(2)
        item.setText(_translate("Employee", "Pay Date", None))
        item = self.bonusTable.horizontalHeaderItem(3)
        item.setText(_translate("Employee", "Period St Date", None))
        self.SalaryDelButt.setText(_translate("Employee", "Delete", None))
        self.BonusDelButt.setText(_translate("Employee", "Delete", None))
        self.finishlabel.setText(_translate("Employee", "Finish Date", None))
        self.finishDateUpdateBUT.setText(_translate("Employee", "Save", None))
        self.BonusUpdateBUT.setText(_translate("Employee", "Save", None))
        self.SalaryUpdateBUT.setText(_translate("Employee", "Save", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.payrollInformationTab), _translate("Employee", "Salary", None))
        item = self.holidayEntitlementTable.horizontalHeaderItem(0)
        item.setText(_translate("Employee", "ID", None))
        item = self.holidayEntitlementTable.horizontalHeaderItem(1)
        item.setText(_translate("Employee", "Entitlement", None))
        item = self.holidayEntitlementTable.horizontalHeaderItem(2)
        item.setText(_translate("Employee", "Adjust Date", None))
        self.holidaylabel.setText(_translate("Employee", "Holiday Entitlement", None))
        self.holidayEntitlementAddBUT.setText(_translate("Employee", "Add", None))
        self.holidayEntitlementDelBUT.setText(_translate("Employee", "Delete", None))
        self.HolidayUpdateBUT.setText(_translate("Employee", "Save", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.HolidayTab), _translate("Employee", "Holiday", None))
        self.UpdateEmpRecordBUT.setText(_translate("Employee", "Save", None))
        self.closeEmployeePopUpBUT.setText(_translate("Employee", "Close", None))

