# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'payrollVariableUI.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(846, 339)
        self.tabWidget = QtGui.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(20, 10, 800, 281))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.pensionNICTableWidget = QtGui.QTableWidget(self.tab_2)
        self.pensionNICTableWidget.setGeometry(QtCore.QRect(0, 0, 800, 251))
        self.pensionNICTableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pensionNICTableWidget.setEditTriggers(QtGui.QAbstractItemView.DoubleClicked)
        self.pensionNICTableWidget.setDragDropOverwriteMode(False)
        self.pensionNICTableWidget.setAlternatingRowColors(True)
        self.pensionNICTableWidget.setColumnCount(8)
        self.pensionNICTableWidget.setObjectName(_fromUtf8("pensionNICTableWidget"))
        self.pensionNICTableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.pensionNICTableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.pensionNICTableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.pensionNICTableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.pensionNICTableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.pensionNICTableWidget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.pensionNICTableWidget.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.pensionNICTableWidget.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.pensionNICTableWidget.setHorizontalHeaderItem(7, item)
        self.pensionNICTableWidget.horizontalHeader().setDefaultSectionSize(115)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.ratesNMWTableWidget = QtGui.QTableWidget(self.tab)
        self.ratesNMWTableWidget.setGeometry(QtCore.QRect(0, 0, 700, 251))
        self.ratesNMWTableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.ratesNMWTableWidget.setEditTriggers(QtGui.QAbstractItemView.DoubleClicked)
        self.ratesNMWTableWidget.setDragDropOverwriteMode(False)
        self.ratesNMWTableWidget.setAlternatingRowColors(True)
        self.ratesNMWTableWidget.setObjectName(_fromUtf8("ratesNMWTableWidget"))
        self.ratesNMWTableWidget.setColumnCount(4)
        self.ratesNMWTableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.ratesNMWTableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.ratesNMWTableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.ratesNMWTableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.ratesNMWTableWidget.setHorizontalHeaderItem(3, item)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.bandsNMWTableWidget = QtGui.QTableWidget(self.tab_3)
        self.bandsNMWTableWidget.setGeometry(QtCore.QRect(0, 0, 800, 251))
        self.bandsNMWTableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.bandsNMWTableWidget.setEditTriggers(QtGui.QAbstractItemView.DoubleClicked)
        self.bandsNMWTableWidget.setDragDropOverwriteMode(False)
        self.bandsNMWTableWidget.setAlternatingRowColors(True)
        self.bandsNMWTableWidget.setObjectName(_fromUtf8("bandsNMWTableWidget"))
        self.bandsNMWTableWidget.setColumnCount(4)
        self.bandsNMWTableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.bandsNMWTableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.bandsNMWTableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.bandsNMWTableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.bandsNMWTableWidget.setHorizontalHeaderItem(3, item)
        self.bandsNMWTableWidget.horizontalHeader().setDefaultSectionSize(100)
        self.bandsNMWTableWidget.horizontalHeader().setStretchLastSection(False)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.updateBUT = QtGui.QPushButton(Dialog)
        self.updateBUT.setGeometry(QtCore.QRect(736, 300, 85, 27))
        self.updateBUT.setObjectName(_fromUtf8("updateBUT"))
        self.addBUT = QtGui.QPushButton(Dialog)
        self.addBUT.setGeometry(QtCore.QRect(20, 300, 85, 27))
        self.addBUT.setAutoDefault(False)
        self.addBUT.setObjectName(_fromUtf8("addBUT"))
        self.delBUT = QtGui.QPushButton(Dialog)
        self.delBUT.setGeometry(QtCore.QRect(110, 300, 85, 27))
        self.delBUT.setAutoDefault(False)
        self.delBUT.setObjectName(_fromUtf8("delBUT"))
        self.closeBUT = QtGui.QPushButton(Dialog)
        self.closeBUT.setGeometry(QtCore.QRect(650, 300, 85, 27))
        self.closeBUT.setAutoDefault(False)
        self.closeBUT.setObjectName(_fromUtf8("closeBUT"))

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.tabWidget, self.pensionNICTableWidget)
        Dialog.setTabOrder(self.pensionNICTableWidget, self.ratesNMWTableWidget)
        Dialog.setTabOrder(self.ratesNMWTableWidget, self.bandsNMWTableWidget)
        Dialog.setTabOrder(self.bandsNMWTableWidget, self.addBUT)
        Dialog.setTabOrder(self.addBUT, self.delBUT)
        Dialog.setTabOrder(self.delBUT, self.closeBUT)
        Dialog.setTabOrder(self.closeBUT, self.updateBUT)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Payroll Variables", None))
        item = self.pensionNICTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "ID", None))
        item = self.pensionNICTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Date", None))
        item = self.pensionNICTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Minimum Age", None))
        item = self.pensionNICTableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "NIC Rate", None))
        item = self.pensionNICTableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "NIC Threshold", None))
        item = self.pensionNICTableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "Pension %", None))
        item = self.pensionNICTableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Dialog", "SSP Day Rate", None))
        item = self.pensionNICTableWidget.horizontalHeaderItem(7)
        item.setText(_translate("Dialog", "SSP LEL", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "NIC and Pension", None))
        item = self.ratesNMWTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "ID", None))
        item = self.ratesNMWTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Band", None))
        item = self.ratesNMWTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Rate", None))
        item = self.ratesNMWTableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Date", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "NMW Rates", None))
        item = self.bandsNMWTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "ID", None))
        item = self.bandsNMWTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Band", None))
        item = self.bandsNMWTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "From", None))
        item = self.bandsNMWTableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "To", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Dialog", "NMW Bands", None))
        self.updateBUT.setText(_translate("Dialog", "Update", None))
        self.addBUT.setText(_translate("Dialog", "Add", None))
        self.delBUT.setText(_translate("Dialog", "Delete", None))
        self.closeBUT.setText(_translate("Dialog", "Close", None))

