# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QtUis/Rotav7.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1288, 552)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setTabShape(QtGui.QTabWidget.Rounded)
        MainWindow.setDockOptions(QtGui.QMainWindow.AllowTabbedDocks|QtGui.QMainWindow.AnimatedDocks)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setContentsMargins(-1, 0, -1, 0)
        self.gridLayout_2.setHorizontalSpacing(6)
        self.gridLayout_2.setVerticalSpacing(2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.tabWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tabWidget.setTabPosition(QtGui.QTabWidget.West)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.rotaTab = QtGui.QWidget()
        self.rotaTab.setObjectName(_fromUtf8("rotaTab"))
        self.gridLayout_5 = QtGui.QGridLayout(self.rotaTab)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.tableWidget = QtGui.QTableWidget(self.rotaTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.tableWidget.setStyleSheet(_fromUtf8(""))
        self.tableWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setDragDropOverwriteMode(False)
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.tableWidget.setSelectionBehavior(QtGui.QAbstractItemView.SelectItems)
        self.tableWidget.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.tableWidget.setWordWrap(True)
        self.tableWidget.setColumnCount(8)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(150)
        self.tableWidget.horizontalHeader().setHighlightSections(False)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(150)
        self.tableWidget.horizontalHeader().setStretchLastSection(False)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget.verticalHeader().setDefaultSectionSize(30)
        self.tableWidget.verticalHeader().setHighlightSections(False)
        self.tableWidget.verticalHeader().setMinimumSectionSize(21)
        self.tableWidget.verticalHeader().setStretchLastSection(False)
        self.gridLayout_5.addWidget(self.tableWidget, 4, 0, 1, 1)
        self.coverHeaderTable = QtGui.QTableWidget(self.rotaTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.coverHeaderTable.sizePolicy().hasHeightForWidth())
        self.coverHeaderTable.setSizePolicy(sizePolicy)
        self.coverHeaderTable.setMinimumSize(QtCore.QSize(0, 25))
        self.coverHeaderTable.setMaximumSize(QtCore.QSize(16777215, 25))
        self.coverHeaderTable.setFrameShadow(QtGui.QFrame.Sunken)
        self.coverHeaderTable.setLineWidth(0)
        self.coverHeaderTable.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.coverHeaderTable.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.coverHeaderTable.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.coverHeaderTable.setTabKeyNavigation(False)
        self.coverHeaderTable.setDragDropOverwriteMode(False)
        self.coverHeaderTable.setColumnCount(8)
        self.coverHeaderTable.setObjectName(_fromUtf8("coverHeaderTable"))
        self.coverHeaderTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.coverHeaderTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.coverHeaderTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.coverHeaderTable.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.coverHeaderTable.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.coverHeaderTable.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.coverHeaderTable.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.coverHeaderTable.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.coverHeaderTable.setHorizontalHeaderItem(7, item)
        self.coverHeaderTable.horizontalHeader().setDefaultSectionSize(150)
        self.coverHeaderTable.horizontalHeader().setMinimumSectionSize(150)
        self.coverHeaderTable.horizontalHeader().setSortIndicatorShown(False)
        self.coverHeaderTable.verticalHeader().setVisible(False)
        self.coverHeaderTable.verticalHeader().setCascadingSectionResizes(False)
        self.coverHeaderTable.verticalHeader().setDefaultSectionSize(0)
        self.gridLayout_5.addWidget(self.coverHeaderTable, 3, 0, 1, 1)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.delShiftBUT = QtGui.QPushButton(self.rotaTab)
        self.delShiftBUT.setMinimumSize(QtCore.QSize(80, 0))
        self.delShiftBUT.setMaximumSize(QtCore.QSize(121, 16777215))
        self.delShiftBUT.setObjectName(_fromUtf8("delShiftBUT"))
        self.gridLayout_3.addWidget(self.delShiftBUT, 0, 15, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 0, 11, 1, 1)
        self.line = QtGui.QFrame(self.rotaTab)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout_3.addWidget(self.line, 0, 20, 1, 1)
        self.departmentFilterCombo = QtGui.QComboBox(self.rotaTab)
        self.departmentFilterCombo.setObjectName(_fromUtf8("departmentFilterCombo"))
        self.gridLayout_3.addWidget(self.departmentFilterCombo, 0, 8, 1, 1)
        self.line_2 = QtGui.QFrame(self.rotaTab)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout_3.addWidget(self.line_2, 0, 17, 1, 1)
        self.label_3 = QtGui.QLabel(self.rotaTab)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_3.addWidget(self.label_3, 0, 6, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 0, 7, 1, 1)
        self.line_10 = QtGui.QFrame(self.rotaTab)
        self.line_10.setFrameShape(QtGui.QFrame.VLine)
        self.line_10.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_10.setObjectName(_fromUtf8("line_10"))
        self.gridLayout_3.addWidget(self.line_10, 0, 10, 1, 1)
        self.deleteWeekBUT = QtGui.QPushButton(self.rotaTab)
        self.deleteWeekBUT.setObjectName(_fromUtf8("deleteWeekBUT"))
        self.gridLayout_3.addWidget(self.deleteWeekBUT, 0, 16, 1, 1)
        self.line_3 = QtGui.QFrame(self.rotaTab)
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.gridLayout_3.addWidget(self.line_3, 0, 14, 1, 1)
        self.AddEmpBUT = QtGui.QPushButton(self.rotaTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AddEmpBUT.sizePolicy().hasHeightForWidth())
        self.AddEmpBUT.setSizePolicy(sizePolicy)
        self.AddEmpBUT.setMaximumSize(QtCore.QSize(16777215, 27))
        self.AddEmpBUT.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.AddEmpBUT.setObjectName(_fromUtf8("AddEmpBUT"))
        self.gridLayout_3.addWidget(self.AddEmpBUT, 0, 19, 1, 1)
        self.AutoPopulate = QtGui.QPushButton(self.rotaTab)
        self.AutoPopulate.setObjectName(_fromUtf8("AutoPopulate"))
        self.gridLayout_3.addWidget(self.AutoPopulate, 0, 13, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(5, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 0, 9, 1, 1)
        self.RemoveEmpBUT = QtGui.QPushButton(self.rotaTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RemoveEmpBUT.sizePolicy().hasHeightForWidth())
        self.RemoveEmpBUT.setSizePolicy(sizePolicy)
        self.RemoveEmpBUT.setMaximumSize(QtCore.QSize(16777215, 27))
        self.RemoveEmpBUT.setObjectName(_fromUtf8("RemoveEmpBUT"))
        self.gridLayout_3.addWidget(self.RemoveEmpBUT, 0, 18, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(5, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem3, 0, 5, 1, 1)
        self.line_8 = QtGui.QFrame(self.rotaTab)
        self.line_8.setFrameShape(QtGui.QFrame.VLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName(_fromUtf8("line_8"))
        self.gridLayout_3.addWidget(self.line_8, 0, 12, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_3, 2, 0, 1, 1)
        self.tabWidget.addTab(self.rotaTab, _fromUtf8(""))
        self.wageTab = QtGui.QWidget()
        self.wageTab.setObjectName(_fromUtf8("wageTab"))
        self.gridLayout_15 = QtGui.QGridLayout(self.wageTab)
        self.gridLayout_15.setObjectName(_fromUtf8("gridLayout_15"))
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.line_7 = QtGui.QFrame(self.wageTab)
        self.line_7.setFrameShape(QtGui.QFrame.VLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.gridLayout_7.addWidget(self.line_7, 0, 1, 1, 1)
        self.line_6 = QtGui.QFrame(self.wageTab)
        self.line_6.setFrameShape(QtGui.QFrame.VLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.gridLayout_7.addWidget(self.line_6, 2, 1, 1, 1)
        self.line_13 = QtGui.QFrame(self.wageTab)
        self.line_13.setFrameShape(QtGui.QFrame.VLine)
        self.line_13.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_13.setObjectName(_fromUtf8("line_13"))
        self.gridLayout_7.addWidget(self.line_13, 4, 1, 1, 1)
        self.line_14 = QtGui.QFrame(self.wageTab)
        self.line_14.setFrameShape(QtGui.QFrame.HLine)
        self.line_14.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_14.setObjectName(_fromUtf8("line_14"))
        self.gridLayout_7.addWidget(self.line_14, 1, 4, 1, 1)
        self.line_9 = QtGui.QFrame(self.wageTab)
        self.line_9.setFrameShape(QtGui.QFrame.VLine)
        self.line_9.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_9.setObjectName(_fromUtf8("line_9"))
        self.gridLayout_7.addWidget(self.line_9, 9, 1, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.wageTab)
        self.groupBox_2.setAutoFillBackground(False)
        self.groupBox_2.setFlat(False)
        self.groupBox_2.setCheckable(False)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.predictedWagePerclbl = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.predictedWagePerclbl.sizePolicy().hasHeightForWidth())
        self.predictedWagePerclbl.setSizePolicy(sizePolicy)
        self.predictedWagePerclbl.setMinimumSize(QtCore.QSize(0, 18))
        self.predictedWagePerclbl.setMaximumSize(QtCore.QSize(90, 16777215))
        self.predictedWagePerclbl.setObjectName(_fromUtf8("predictedWagePerclbl"))
        self.gridLayout_4.addWidget(self.predictedWagePerclbl, 2, 0, 1, 1)
        self.predSalariedlbl = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.predSalariedlbl.sizePolicy().hasHeightForWidth())
        self.predSalariedlbl.setSizePolicy(sizePolicy)
        self.predSalariedlbl.setMinimumSize(QtCore.QSize(0, 18))
        self.predSalariedlbl.setMaximumSize(QtCore.QSize(90, 16777215))
        self.predSalariedlbl.setObjectName(_fromUtf8("predSalariedlbl"))
        self.gridLayout_4.addWidget(self.predSalariedlbl, 1, 0, 1, 1)
        self.predWagelbl = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.predWagelbl.sizePolicy().hasHeightForWidth())
        self.predWagelbl.setSizePolicy(sizePolicy)
        self.predWagelbl.setMinimumSize(QtCore.QSize(0, 18))
        self.predWagelbl.setMaximumSize(QtCore.QSize(90, 16777215))
        self.predWagelbl.setObjectName(_fromUtf8("predWagelbl"))
        self.gridLayout_4.addWidget(self.predWagelbl, 3, 0, 1, 1)
        self.predHourlylbl = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.predHourlylbl.sizePolicy().hasHeightForWidth())
        self.predHourlylbl.setSizePolicy(sizePolicy)
        self.predHourlylbl.setMinimumSize(QtCore.QSize(0, 18))
        self.predHourlylbl.setMaximumSize(QtCore.QSize(90, 16777215))
        self.predHourlylbl.setObjectName(_fromUtf8("predHourlylbl"))
        self.gridLayout_4.addWidget(self.predHourlylbl, 0, 0, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem4, 4, 1, 1, 1)
        self.predWageBox = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.predWageBox.setMinimumSize(QtCore.QSize(79, 18))
        self.predWageBox.setMaximumSize(QtCore.QSize(79, 18))
        self.predWageBox.setReadOnly(True)
        self.predWageBox.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.predWageBox.setDecimals(0)
        self.predWageBox.setMaximum(99999.0)
        self.predWageBox.setObjectName(_fromUtf8("predWageBox"))
        self.gridLayout_4.addWidget(self.predWageBox, 3, 1, 1, 1)
        self.predSalariedBox = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.predSalariedBox.setMinimumSize(QtCore.QSize(79, 18))
        self.predSalariedBox.setMaximumSize(QtCore.QSize(79, 18))
        self.predSalariedBox.setReadOnly(True)
        self.predSalariedBox.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.predSalariedBox.setDecimals(0)
        self.predSalariedBox.setMaximum(999999.0)
        self.predSalariedBox.setObjectName(_fromUtf8("predSalariedBox"))
        self.gridLayout_4.addWidget(self.predSalariedBox, 1, 1, 1, 1)
        self.predHourlyBox = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.predHourlyBox.setMinimumSize(QtCore.QSize(79, 18))
        self.predHourlyBox.setMaximumSize(QtCore.QSize(79, 18))
        self.predHourlyBox.setReadOnly(True)
        self.predHourlyBox.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.predHourlyBox.setDecimals(0)
        self.predHourlyBox.setMaximum(999999.0)
        self.predHourlyBox.setObjectName(_fromUtf8("predHourlyBox"))
        self.gridLayout_4.addWidget(self.predHourlyBox, 0, 1, 1, 1)
        self.predWagePercBox = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.predWagePercBox.setMinimumSize(QtCore.QSize(79, 18))
        self.predWagePercBox.setMaximumSize(QtCore.QSize(79, 18))
        self.predWagePercBox.setReadOnly(True)
        self.predWagePercBox.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.predWagePercBox.setMaximum(999.99)
        self.predWagePercBox.setObjectName(_fromUtf8("predWagePercBox"))
        self.gridLayout_4.addWidget(self.predWagePercBox, 2, 1, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox_2, 0, 2, 1, 1)
        self.line_4 = QtGui.QFrame(self.wageTab)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.gridLayout_7.addWidget(self.line_4, 1, 2, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.wageTab)
        self.groupBox.setAutoFillBackground(False)
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.predBonuslbl = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.predBonuslbl.sizePolicy().hasHeightForWidth())
        self.predBonuslbl.setSizePolicy(sizePolicy)
        self.predBonuslbl.setMaximumSize(QtCore.QSize(90, 16777215))
        self.predBonuslbl.setObjectName(_fromUtf8("predBonuslbl"))
        self.gridLayout.addWidget(self.predBonuslbl, 1, 0, 1, 1)
        self.predPensionlbl = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.predPensionlbl.sizePolicy().hasHeightForWidth())
        self.predPensionlbl.setSizePolicy(sizePolicy)
        self.predPensionlbl.setMaximumSize(QtCore.QSize(90, 16777215))
        self.predPensionlbl.setObjectName(_fromUtf8("predPensionlbl"))
        self.gridLayout.addWidget(self.predPensionlbl, 0, 0, 1, 1)
        self.predBonusBox = QtGui.QDoubleSpinBox(self.groupBox)
        self.predBonusBox.setMinimumSize(QtCore.QSize(79, 18))
        self.predBonusBox.setMaximumSize(QtCore.QSize(79, 18))
        self.predBonusBox.setReadOnly(True)
        self.predBonusBox.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.predBonusBox.setDecimals(0)
        self.predBonusBox.setMaximum(9999.0)
        self.predBonusBox.setObjectName(_fromUtf8("predBonusBox"))
        self.gridLayout.addWidget(self.predBonusBox, 1, 1, 1, 1)
        self.predPensionBox = QtGui.QDoubleSpinBox(self.groupBox)
        self.predPensionBox.setMinimumSize(QtCore.QSize(79, 18))
        self.predPensionBox.setMaximumSize(QtCore.QSize(79, 18))
        self.predPensionBox.setReadOnly(True)
        self.predPensionBox.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.predPensionBox.setDecimals(0)
        self.predPensionBox.setMaximum(9999.0)
        self.predPensionBox.setObjectName(_fromUtf8("predPensionBox"))
        self.gridLayout.addWidget(self.predPensionBox, 0, 1, 1, 1)
        self.predNICBox = QtGui.QDoubleSpinBox(self.groupBox)
        self.predNICBox.setMinimumSize(QtCore.QSize(79, 18))
        self.predNICBox.setMaximumSize(QtCore.QSize(79, 18))
        self.predNICBox.setReadOnly(True)
        self.predNICBox.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.predNICBox.setDecimals(0)
        self.predNICBox.setMaximum(9999.0)
        self.predNICBox.setObjectName(_fromUtf8("predNICBox"))
        self.gridLayout.addWidget(self.predNICBox, 2, 1, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem5, 4, 1, 1, 1)
        self.predNIClbl = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.predNIClbl.sizePolicy().hasHeightForWidth())
        self.predNIClbl.setSizePolicy(sizePolicy)
        self.predNIClbl.setMaximumSize(QtCore.QSize(90, 16777215))
        self.predNIClbl.setObjectName(_fromUtf8("predNIClbl"))
        self.gridLayout.addWidget(self.predNIClbl, 2, 0, 1, 1)
        self.predSSPBox = QtGui.QDoubleSpinBox(self.groupBox)
        self.predSSPBox.setMinimumSize(QtCore.QSize(79, 18))
        self.predSSPBox.setMaximumSize(QtCore.QSize(16777215, 18))
        self.predSSPBox.setReadOnly(True)
        self.predSSPBox.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.predSSPBox.setDecimals(0)
        self.predSSPBox.setObjectName(_fromUtf8("predSSPBox"))
        self.gridLayout.addWidget(self.predSSPBox, 3, 1, 1, 1)
        self.PredSSPlbl = QtGui.QLabel(self.groupBox)
        self.PredSSPlbl.setObjectName(_fromUtf8("PredSSPlbl"))
        self.gridLayout.addWidget(self.PredSSPlbl, 3, 0, 1, 1)
        self.predNICBox.raise_()
        self.predBonuslbl.raise_()
        self.predBonusBox.raise_()
        self.predNIClbl.raise_()
        self.predPensionlbl.raise_()
        self.predPensionBox.raise_()
        self.predSSPBox.raise_()
        self.PredSSPlbl.raise_()
        self.gridLayout_7.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_4 = QtGui.QGroupBox(self.wageTab)
        self.groupBox_4.setAutoFillBackground(False)
        self.groupBox_4.setFlat(False)
        self.groupBox_4.setCheckable(False)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout_12 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.wtdWageLbl = QtGui.QLabel(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wtdWageLbl.sizePolicy().hasHeightForWidth())
        self.wtdWageLbl.setSizePolicy(sizePolicy)
        self.wtdWageLbl.setMinimumSize(QtCore.QSize(0, 18))
        self.wtdWageLbl.setMaximumSize(QtCore.QSize(90, 16777215))
        self.wtdWageLbl.setObjectName(_fromUtf8("wtdWageLbl"))
        self.gridLayout_12.addWidget(self.wtdWageLbl, 0, 0, 1, 1)
        self.wtdRevBox = QtGui.QDoubleSpinBox(self.groupBox_4)
        self.wtdRevBox.setMinimumSize(QtCore.QSize(79, 18))
        self.wtdRevBox.setMaximumSize(QtCore.QSize(79, 18))
        self.wtdRevBox.setReadOnly(True)
        self.wtdRevBox.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.wtdRevBox.setDecimals(0)
        self.wtdRevBox.setMaximum(99999.0)
        self.wtdRevBox.setObjectName(_fromUtf8("wtdRevBox"))
        self.gridLayout_12.addWidget(self.wtdRevBox, 1, 1, 1, 1)
        self.wtdWageBox = QtGui.QDoubleSpinBox(self.groupBox_4)
        self.wtdWageBox.setMinimumSize(QtCore.QSize(79, 18))
        self.wtdWageBox.setMaximumSize(QtCore.QSize(79, 18))
        self.wtdWageBox.setReadOnly(True)
        self.wtdWageBox.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.wtdWageBox.setDecimals(0)
        self.wtdWageBox.setMaximum(9999.0)
        self.wtdWageBox.setObjectName(_fromUtf8("wtdWageBox"))
        self.gridLayout_12.addWidget(self.wtdWageBox, 0, 1, 1, 1)
        self.wtdWagePerclbl = QtGui.QLabel(self.groupBox_4)
        self.wtdWagePerclbl.setMinimumSize(QtCore.QSize(0, 18))
        self.wtdWagePerclbl.setObjectName(_fromUtf8("wtdWagePerclbl"))
        self.gridLayout_12.addWidget(self.wtdWagePerclbl, 2, 0, 1, 1)
        self.wtdWagePercBox = QtGui.QDoubleSpinBox(self.groupBox_4)
        self.wtdWagePercBox.setMinimumSize(QtCore.QSize(79, 18))
        self.wtdWagePercBox.setMaximumSize(QtCore.QSize(79, 18))
        self.wtdWagePercBox.setReadOnly(True)
        self.wtdWagePercBox.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.wtdWagePercBox.setObjectName(_fromUtf8("wtdWagePercBox"))
        self.gridLayout_12.addWidget(self.wtdWagePercBox, 2, 1, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_12.addItem(spacerItem6, 4, 0, 1, 1)
        self.wtdAVGSpendlbl = QtGui.QLabel(self.groupBox_4)
        self.wtdAVGSpendlbl.setMinimumSize(QtCore.QSize(0, 18))
        self.wtdAVGSpendlbl.setObjectName(_fromUtf8("wtdAVGSpendlbl"))
        self.gridLayout_12.addWidget(self.wtdAVGSpendlbl, 3, 0, 1, 1)
        self.wtdAvgSpendBox = QtGui.QDoubleSpinBox(self.groupBox_4)
        self.wtdAvgSpendBox.setMinimumSize(QtCore.QSize(79, 18))
        self.wtdAvgSpendBox.setMaximumSize(QtCore.QSize(79, 18))
        self.wtdAvgSpendBox.setReadOnly(True)
        self.wtdAvgSpendBox.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.wtdAvgSpendBox.setMaximum(999.0)
        self.wtdAvgSpendBox.setObjectName(_fromUtf8("wtdAvgSpendBox"))
        self.gridLayout_12.addWidget(self.wtdAvgSpendBox, 3, 1, 1, 1)
        self.wtdRevlbl = QtGui.QLabel(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wtdRevlbl.sizePolicy().hasHeightForWidth())
        self.wtdRevlbl.setSizePolicy(sizePolicy)
        self.wtdRevlbl.setMinimumSize(QtCore.QSize(0, 18))
        self.wtdRevlbl.setMaximumSize(QtCore.QSize(90, 16777215))
        self.wtdRevlbl.setObjectName(_fromUtf8("wtdRevlbl"))
        self.gridLayout_12.addWidget(self.wtdRevlbl, 1, 0, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox_4, 4, 0, 1, 1)
        self.line_11 = QtGui.QFrame(self.wageTab)
        self.line_11.setFrameShape(QtGui.QFrame.VLine)
        self.line_11.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_11.setObjectName(_fromUtf8("line_11"))
        self.gridLayout_7.addWidget(self.line_11, 4, 3, 1, 1)
        self.line_12 = QtGui.QFrame(self.wageTab)
        self.line_12.setFrameShape(QtGui.QFrame.HLine)
        self.line_12.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_12.setObjectName(_fromUtf8("line_12"))
        self.gridLayout_7.addWidget(self.line_12, 1, 0, 1, 1)
        self.line_5 = QtGui.QFrame(self.wageTab)
        self.line_5.setFrameShape(QtGui.QFrame.VLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.gridLayout_7.addWidget(self.line_5, 0, 3, 1, 1)
        self.groupBox_5 = QtGui.QGroupBox(self.wageTab)
        self.groupBox_5.setAutoFillBackground(False)
        self.groupBox_5.setFlat(False)
        self.groupBox_5.setCheckable(False)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.gridLayout_13 = QtGui.QGridLayout(self.groupBox_5)
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.mtdWageBox = QtGui.QDoubleSpinBox(self.groupBox_5)
        self.mtdWageBox.setMinimumSize(QtCore.QSize(79, 18))
        self.mtdWageBox.setMaximumSize(QtCore.QSize(79, 18))
        self.mtdWageBox.setReadOnly(True)
        self.mtdWageBox.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.mtdWageBox.setDecimals(0)
        self.mtdWageBox.setMaximum(10000000.0)
        self.mtdWageBox.setObjectName(_fromUtf8("mtdWageBox"))
        self.gridLayout_13.addWidget(self.mtdWageBox, 0, 1, 1, 1)
        self.mtdRevenue = QtGui.QLabel(self.groupBox_5)
        self.mtdRevenue.setMinimumSize(QtCore.QSize(0, 18))
        self.mtdRevenue.setObjectName(_fromUtf8("mtdRevenue"))
        self.gridLayout_13.addWidget(self.mtdRevenue, 1, 0, 1, 1)
        self.mtdRevBox = QtGui.QDoubleSpinBox(self.groupBox_5)
        self.mtdRevBox.setMinimumSize(QtCore.QSize(79, 18))
        self.mtdRevBox.setMaximumSize(QtCore.QSize(79, 18))
        self.mtdRevBox.setReadOnly(True)
        self.mtdRevBox.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.mtdRevBox.setDecimals(0)
        self.mtdRevBox.setMaximum(99999.0)
        self.mtdRevBox.setObjectName(_fromUtf8("mtdRevBox"))
        self.gridLayout_13.addWidget(self.mtdRevBox, 1, 1, 1, 1)
        self.mtdWagePerc = QtGui.QLabel(self.groupBox_5)
        self.mtdWagePerc.setMinimumSize(QtCore.QSize(0, 18))
        self.mtdWagePerc.setObjectName(_fromUtf8("mtdWagePerc"))
        self.gridLayout_13.addWidget(self.mtdWagePerc, 2, 0, 1, 1)
        self.mtdWagePercBox = QtGui.QDoubleSpinBox(self.groupBox_5)
        self.mtdWagePercBox.setMinimumSize(QtCore.QSize(79, 18))
        self.mtdWagePercBox.setMaximumSize(QtCore.QSize(79, 18))
        self.mtdWagePercBox.setReadOnly(True)
        self.mtdWagePercBox.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.mtdWagePercBox.setMaximum(10000.0)
        self.mtdWagePercBox.setObjectName(_fromUtf8("mtdWagePercBox"))
        self.gridLayout_13.addWidget(self.mtdWagePercBox, 2, 1, 1, 1)
        self.mtdAvgSpend = QtGui.QLabel(self.groupBox_5)
        self.mtdAvgSpend.setMinimumSize(QtCore.QSize(0, 18))
        self.mtdAvgSpend.setObjectName(_fromUtf8("mtdAvgSpend"))
        self.gridLayout_13.addWidget(self.mtdAvgSpend, 3, 0, 1, 1)
        self.mtdAvgSpendBox = QtGui.QDoubleSpinBox(self.groupBox_5)
        self.mtdAvgSpendBox.setMinimumSize(QtCore.QSize(79, 18))
        self.mtdAvgSpendBox.setMaximumSize(QtCore.QSize(79, 18))
        self.mtdAvgSpendBox.setReadOnly(True)
        self.mtdAvgSpendBox.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.mtdAvgSpendBox.setMaximum(999.0)
        self.mtdAvgSpendBox.setObjectName(_fromUtf8("mtdAvgSpendBox"))
        self.gridLayout_13.addWidget(self.mtdAvgSpendBox, 3, 1, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_13.addItem(spacerItem7, 4, 0, 1, 1)
        self.mtdWage = QtGui.QLabel(self.groupBox_5)
        self.mtdWage.setMinimumSize(QtCore.QSize(0, 18))
        self.mtdWage.setObjectName(_fromUtf8("mtdWage"))
        self.gridLayout_13.addWidget(self.mtdWage, 0, 0, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox_5, 4, 2, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(self.wageTab)
        self.groupBox_3.setAutoFillBackground(False)
        self.groupBox_3.setFlat(False)
        self.groupBox_3.setCheckable(False)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_10 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.predRevlbl = QtGui.QLabel(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.predRevlbl.sizePolicy().hasHeightForWidth())
        self.predRevlbl.setSizePolicy(sizePolicy)
        self.predRevlbl.setMinimumSize(QtCore.QSize(0, 18))
        self.predRevlbl.setMaximumSize(QtCore.QSize(90, 16777215))
        self.predRevlbl.setObjectName(_fromUtf8("predRevlbl"))
        self.gridLayout_10.addWidget(self.predRevlbl, 0, 0, 1, 1)
        self.predRevBox = QtGui.QDoubleSpinBox(self.groupBox_3)
        self.predRevBox.setMinimumSize(QtCore.QSize(79, 18))
        self.predRevBox.setMaximumSize(QtCore.QSize(79, 18))
        self.predRevBox.setReadOnly(True)
        self.predRevBox.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.predRevBox.setDecimals(0)
        self.predRevBox.setMaximum(99999.0)
        self.predRevBox.setObjectName(_fromUtf8("predRevBox"))
        self.gridLayout_10.addWidget(self.predRevBox, 0, 1, 1, 1)
        self.predAvgSpendBox = QtGui.QDoubleSpinBox(self.groupBox_3)
        self.predAvgSpendBox.setMinimumSize(QtCore.QSize(79, 18))
        self.predAvgSpendBox.setMaximumSize(QtCore.QSize(79, 18))
        self.predAvgSpendBox.setReadOnly(True)
        self.predAvgSpendBox.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.predAvgSpendBox.setMaximum(999.0)
        self.predAvgSpendBox.setObjectName(_fromUtf8("predAvgSpendBox"))
        self.gridLayout_10.addWidget(self.predAvgSpendBox, 1, 1, 1, 1)
        spacerItem8 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_10.addItem(spacerItem8, 2, 1, 1, 1)
        self.predAVGSpendlbl = QtGui.QLabel(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.predAVGSpendlbl.sizePolicy().hasHeightForWidth())
        self.predAVGSpendlbl.setSizePolicy(sizePolicy)
        self.predAVGSpendlbl.setMinimumSize(QtCore.QSize(0, 18))
        self.predAVGSpendlbl.setMaximumSize(QtCore.QSize(90, 16777215))
        self.predAVGSpendlbl.setObjectName(_fromUtf8("predAVGSpendlbl"))
        self.gridLayout_10.addWidget(self.predAVGSpendlbl, 1, 0, 1, 1)
        spacerItem9 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_10.addItem(spacerItem9, 2, 0, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox_3, 0, 4, 1, 1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.exAdminCheck = QtGui.QCheckBox(self.wageTab)
        self.exAdminCheck.setObjectName(_fromUtf8("exAdminCheck"))
        self.horizontalLayout_2.addWidget(self.exAdminCheck)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout_7.addLayout(self.verticalLayout, 4, 4, 1, 1)
        spacerItem10 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem10, 6, 4, 1, 1)
        self.gridLayout_15.addLayout(self.gridLayout_7, 0, 2, 1, 1)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_15.addItem(spacerItem11, 0, 4, 1, 1)
        self.tabWidget.addTab(self.wageTab, _fromUtf8(""))
        self.coverTab = QtGui.QWidget()
        self.coverTab.setObjectName(_fromUtf8("coverTab"))
        self.gridLayout_6 = QtGui.QGridLayout(self.coverTab)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.gridLayout_8 = QtGui.QGridLayout()
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.gridLayout_11 = QtGui.QGridLayout()
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem12, 0, 4, 1, 1)
        self.YTDCoverslbl = QtGui.QLabel(self.coverTab)
        self.YTDCoverslbl.setObjectName(_fromUtf8("YTDCoverslbl"))
        self.gridLayout_11.addWidget(self.YTDCoverslbl, 2, 2, 1, 1)
        spacerItem13 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_11.addItem(spacerItem13, 7, 3, 1, 1)
        self.MTDCoversLbl = QtGui.QLabel(self.coverTab)
        self.MTDCoversLbl.setObjectName(_fromUtf8("MTDCoversLbl"))
        self.gridLayout_11.addWidget(self.MTDCoversLbl, 0, 2, 1, 1)
        self.YTDCoversTotalBox = QtGui.QSpinBox(self.coverTab)
        self.YTDCoversTotalBox.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.YTDCoversTotalBox.setMaximum(50000)
        self.YTDCoversTotalBox.setObjectName(_fromUtf8("YTDCoversTotalBox"))
        self.gridLayout_11.addWidget(self.YTDCoversTotalBox, 3, 2, 1, 1)
        self.WeeklyCoversTotalLBL = QtGui.QLabel(self.coverTab)
        self.WeeklyCoversTotalLBL.setObjectName(_fromUtf8("WeeklyCoversTotalLBL"))
        self.gridLayout_11.addWidget(self.WeeklyCoversTotalLBL, 5, 2, 1, 1)
        self.WeeklyCoversTotal = QtGui.QSpinBox(self.coverTab)
        self.WeeklyCoversTotal.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.WeeklyCoversTotal.setMaximum(1000)
        self.WeeklyCoversTotal.setObjectName(_fromUtf8("WeeklyCoversTotal"))
        self.gridLayout_11.addWidget(self.WeeklyCoversTotal, 6, 2, 1, 1)
        self.MTDCoversTotalBox = QtGui.QSpinBox(self.coverTab)
        self.MTDCoversTotalBox.setMinimumSize(QtCore.QSize(100, 0))
        self.MTDCoversTotalBox.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.MTDCoversTotalBox.setMaximum(5000)
        self.MTDCoversTotalBox.setObjectName(_fromUtf8("MTDCoversTotalBox"))
        self.gridLayout_11.addWidget(self.MTDCoversTotalBox, 1, 2, 1, 1)
        self.coverUpdateBUT = QtGui.QPushButton(self.coverTab)
        self.coverUpdateBUT.setMinimumSize(QtCore.QSize(122, 0))
        self.coverUpdateBUT.setObjectName(_fromUtf8("coverUpdateBUT"))
        self.gridLayout_11.addWidget(self.coverUpdateBUT, 7, 2, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_11, 1, 1, 1, 1)
        self.revenueTypeTable = QtGui.QTableWidget(self.coverTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.revenueTypeTable.sizePolicy().hasHeightForWidth())
        self.revenueTypeTable.setSizePolicy(sizePolicy)
        self.revenueTypeTable.setMinimumSize(QtCore.QSize(600, 200))
        self.revenueTypeTable.setMaximumSize(QtCore.QSize(600, 16777215))
        self.revenueTypeTable.setAlternatingRowColors(True)
        self.revenueTypeTable.setIconSize(QtCore.QSize(5, 0))
        self.revenueTypeTable.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.revenueTypeTable.setObjectName(_fromUtf8("revenueTypeTable"))
        self.revenueTypeTable.setColumnCount(0)
        self.revenueTypeTable.setRowCount(0)
        self.revenueTypeTable.horizontalHeader().setMinimumSectionSize(1)
        self.revenueTypeTable.verticalHeader().setMinimumSectionSize(1)
        self.gridLayout_8.addWidget(self.revenueTypeTable, 6, 0, 1, 1)
        self.predictedCoverTable = QtGui.QTableWidget(self.coverTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.predictedCoverTable.sizePolicy().hasHeightForWidth())
        self.predictedCoverTable.setSizePolicy(sizePolicy)
        self.predictedCoverTable.setMinimumSize(QtCore.QSize(892, 200))
        self.predictedCoverTable.setMaximumSize(QtCore.QSize(892, 16777215))
        self.predictedCoverTable.setEditTriggers(QtGui.QAbstractItemView.CurrentChanged|QtGui.QAbstractItemView.DoubleClicked|QtGui.QAbstractItemView.SelectedClicked)
        self.predictedCoverTable.setAlternatingRowColors(True)
        self.predictedCoverTable.setIconSize(QtCore.QSize(5, 0))
        self.predictedCoverTable.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.predictedCoverTable.setColumnCount(15)
        self.predictedCoverTable.setObjectName(_fromUtf8("predictedCoverTable"))
        self.predictedCoverTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.predictedCoverTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.predictedCoverTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.predictedCoverTable.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.predictedCoverTable.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.predictedCoverTable.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.predictedCoverTable.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.predictedCoverTable.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.predictedCoverTable.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.predictedCoverTable.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.predictedCoverTable.setHorizontalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.predictedCoverTable.setHorizontalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.predictedCoverTable.setHorizontalHeaderItem(11, item)
        item = QtGui.QTableWidgetItem()
        self.predictedCoverTable.setHorizontalHeaderItem(12, item)
        item = QtGui.QTableWidgetItem()
        self.predictedCoverTable.setHorizontalHeaderItem(13, item)
        item = QtGui.QTableWidgetItem()
        self.predictedCoverTable.setHorizontalHeaderItem(14, item)
        self.predictedCoverTable.horizontalHeader().setCascadingSectionResizes(False)
        self.predictedCoverTable.horizontalHeader().setMinimumSectionSize(55)
        self.predictedCoverTable.horizontalHeader().setStretchLastSection(False)
        self.predictedCoverTable.verticalHeader().setCascadingSectionResizes(False)
        self.predictedCoverTable.verticalHeader().setDefaultSectionSize(21)
        self.predictedCoverTable.verticalHeader().setMinimumSectionSize(21)
        self.predictedCoverTable.verticalHeader().setStretchLastSection(False)
        self.gridLayout_8.addWidget(self.predictedCoverTable, 1, 0, 1, 1)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.addRevTypeBUT = QtGui.QPushButton(self.coverTab)
        self.addRevTypeBUT.setObjectName(_fromUtf8("addRevTypeBUT"))
        self.horizontalLayout_5.addWidget(self.addRevTypeBUT)
        spacerItem14 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem14)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.delRevenueTypeBUT = QtGui.QPushButton(self.coverTab)
        self.delRevenueTypeBUT.setMinimumSize(QtCore.QSize(122, 0))
        self.delRevenueTypeBUT.setObjectName(_fromUtf8("delRevenueTypeBUT"))
        self.horizontalLayout_6.addWidget(self.delRevenueTypeBUT)
        spacerItem15 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem15)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        spacerItem16 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem16)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        spacerItem17 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem17)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.gridLayout_8.addLayout(self.verticalLayout_2, 6, 1, 1, 1)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.spacerDateLBL = QtGui.QLabel(self.coverTab)
        self.spacerDateLBL.setMinimumSize(QtCore.QSize(109, 0))
        self.spacerDateLBL.setMaximumSize(QtCore.QSize(109, 16777215))
        self.spacerDateLBL.setText(_fromUtf8(""))
        self.spacerDateLBL.setObjectName(_fromUtf8("spacerDateLBL"))
        self.horizontalLayout_8.addWidget(self.spacerDateLBL)
        self.line_21 = QtGui.QFrame(self.coverTab)
        self.line_21.setFrameShape(QtGui.QFrame.VLine)
        self.line_21.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_21.setObjectName(_fromUtf8("line_21"))
        self.horizontalLayout_8.addWidget(self.line_21)
        self.monDateLBL = QtGui.QLabel(self.coverTab)
        self.monDateLBL.setMinimumSize(QtCore.QSize(96, 0))
        self.monDateLBL.setMaximumSize(QtCore.QSize(96, 16777215))
        self.monDateLBL.setAlignment(QtCore.Qt.AlignCenter)
        self.monDateLBL.setObjectName(_fromUtf8("monDateLBL"))
        self.horizontalLayout_8.addWidget(self.monDateLBL)
        self.line_20 = QtGui.QFrame(self.coverTab)
        self.line_20.setFrameShape(QtGui.QFrame.VLine)
        self.line_20.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_20.setObjectName(_fromUtf8("line_20"))
        self.horizontalLayout_8.addWidget(self.line_20)
        self.tueDateLBL = QtGui.QLabel(self.coverTab)
        self.tueDateLBL.setMinimumSize(QtCore.QSize(96, 0))
        self.tueDateLBL.setMaximumSize(QtCore.QSize(96, 16777215))
        self.tueDateLBL.setAlignment(QtCore.Qt.AlignCenter)
        self.tueDateLBL.setObjectName(_fromUtf8("tueDateLBL"))
        self.horizontalLayout_8.addWidget(self.tueDateLBL)
        self.line_19 = QtGui.QFrame(self.coverTab)
        self.line_19.setFrameShape(QtGui.QFrame.VLine)
        self.line_19.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_19.setObjectName(_fromUtf8("line_19"))
        self.horizontalLayout_8.addWidget(self.line_19)
        self.wedDateLBL = QtGui.QLabel(self.coverTab)
        self.wedDateLBL.setMinimumSize(QtCore.QSize(96, 0))
        self.wedDateLBL.setMaximumSize(QtCore.QSize(96, 16777215))
        self.wedDateLBL.setAlignment(QtCore.Qt.AlignCenter)
        self.wedDateLBL.setObjectName(_fromUtf8("wedDateLBL"))
        self.horizontalLayout_8.addWidget(self.wedDateLBL)
        self.line_18 = QtGui.QFrame(self.coverTab)
        self.line_18.setFrameShape(QtGui.QFrame.VLine)
        self.line_18.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_18.setObjectName(_fromUtf8("line_18"))
        self.horizontalLayout_8.addWidget(self.line_18)
        self.thurDateLBL = QtGui.QLabel(self.coverTab)
        self.thurDateLBL.setMinimumSize(QtCore.QSize(96, 0))
        self.thurDateLBL.setMaximumSize(QtCore.QSize(96, 16777215))
        self.thurDateLBL.setAlignment(QtCore.Qt.AlignCenter)
        self.thurDateLBL.setObjectName(_fromUtf8("thurDateLBL"))
        self.horizontalLayout_8.addWidget(self.thurDateLBL)
        self.line_17 = QtGui.QFrame(self.coverTab)
        self.line_17.setFrameShape(QtGui.QFrame.VLine)
        self.line_17.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_17.setObjectName(_fromUtf8("line_17"))
        self.horizontalLayout_8.addWidget(self.line_17)
        self.friDateLBL = QtGui.QLabel(self.coverTab)
        self.friDateLBL.setMinimumSize(QtCore.QSize(96, 0))
        self.friDateLBL.setMaximumSize(QtCore.QSize(96, 16777215))
        self.friDateLBL.setAlignment(QtCore.Qt.AlignCenter)
        self.friDateLBL.setObjectName(_fromUtf8("friDateLBL"))
        self.horizontalLayout_8.addWidget(self.friDateLBL)
        self.line_16 = QtGui.QFrame(self.coverTab)
        self.line_16.setFrameShape(QtGui.QFrame.VLine)
        self.line_16.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_16.setObjectName(_fromUtf8("line_16"))
        self.horizontalLayout_8.addWidget(self.line_16)
        self.satDateLBL = QtGui.QLabel(self.coverTab)
        self.satDateLBL.setMinimumSize(QtCore.QSize(96, 0))
        self.satDateLBL.setMaximumSize(QtCore.QSize(96, 16777215))
        self.satDateLBL.setAlignment(QtCore.Qt.AlignCenter)
        self.satDateLBL.setObjectName(_fromUtf8("satDateLBL"))
        self.horizontalLayout_8.addWidget(self.satDateLBL)
        self.line_15 = QtGui.QFrame(self.coverTab)
        self.line_15.setFrameShape(QtGui.QFrame.VLine)
        self.line_15.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_15.setObjectName(_fromUtf8("line_15"))
        self.horizontalLayout_8.addWidget(self.line_15)
        self.sunDateLBL = QtGui.QLabel(self.coverTab)
        self.sunDateLBL.setMinimumSize(QtCore.QSize(96, 0))
        self.sunDateLBL.setMaximumSize(QtCore.QSize(96, 16777215))
        self.sunDateLBL.setAlignment(QtCore.Qt.AlignCenter)
        self.sunDateLBL.setObjectName(_fromUtf8("sunDateLBL"))
        self.horizontalLayout_8.addWidget(self.sunDateLBL)
        self.line_22 = QtGui.QFrame(self.coverTab)
        self.line_22.setFrameShape(QtGui.QFrame.VLine)
        self.line_22.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_22.setObjectName(_fromUtf8("line_22"))
        self.horizontalLayout_8.addWidget(self.line_22)
        self.gridLayout_8.addLayout(self.horizontalLayout_8, 0, 0, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_8, 4, 1, 1, 1)
        self.tabWidget.addTab(self.coverTab, _fromUtf8(""))
        self.horizontalLayout.addWidget(self.tabWidget)
        self.gridLayout_2.addLayout(self.horizontalLayout, 5, 0, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.dateEdit = QtGui.QDateEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dateEdit.sizePolicy().hasHeightForWidth())
        self.dateEdit.setSizePolicy(sizePolicy)
        self.dateEdit.setMinimumSize(QtCore.QSize(150, 0))
        self.dateEdit.setMaximumSize(QtCore.QSize(200, 27))
        self.dateEdit.setCurrentSection(QtGui.QDateTimeEdit.MonthSection)
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName(_fromUtf8("dateEdit"))
        self.horizontalLayout_4.addWidget(self.dateEdit)
        self.lessWeekBUT = QtGui.QPushButton(self.centralwidget)
        self.lessWeekBUT.setMaximumSize(QtCore.QSize(30, 16777215))
        self.lessWeekBUT.setText(_fromUtf8(""))
        self.lessWeekBUT.setFlat(True)
        self.lessWeekBUT.setObjectName(_fromUtf8("lessWeekBUT"))
        self.horizontalLayout_4.addWidget(self.lessWeekBUT)
        self.todayBut = QtGui.QPushButton(self.centralwidget)
        self.todayBut.setMaximumSize(QtCore.QSize(30, 16777215))
        self.todayBut.setText(_fromUtf8(""))
        self.todayBut.setFlat(True)
        self.todayBut.setObjectName(_fromUtf8("todayBut"))
        self.horizontalLayout_4.addWidget(self.todayBut)
        self.moreWeekBUT = QtGui.QPushButton(self.centralwidget)
        self.moreWeekBUT.setMaximumSize(QtCore.QSize(30, 16777215))
        self.moreWeekBUT.setText(_fromUtf8(""))
        self.moreWeekBUT.setFlat(True)
        self.moreWeekBUT.setObjectName(_fromUtf8("moreWeekBUT"))
        self.horizontalLayout_4.addWidget(self.moreWeekBUT)
        spacerItem18 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem18)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 3, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1288, 27))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuReporting = QtGui.QMenu(self.menuBar)
        self.menuReporting.setObjectName(_fromUtf8("menuReporting"))
        self.menuFile = QtGui.QMenu(self.menuBar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuHolidays = QtGui.QMenu(self.menuBar)
        self.menuHolidays.setObjectName(_fromUtf8("menuHolidays"))
        self.menuFunctions = QtGui.QMenu(self.menuBar)
        self.menuFunctions.setObjectName(_fromUtf8("menuFunctions"))
        MainWindow.setMenuBar(self.menuBar)
        self.actionEmployee = QtGui.QAction(MainWindow)
        self.actionEmployee.setObjectName(_fromUtf8("actionEmployee"))
        self.actionCover_forecast_by_type = QtGui.QAction(MainWindow)
        self.actionCover_forecast_by_type.setObjectName(_fromUtf8("actionCover_forecast_by_type"))
        self.actionCover_Types = QtGui.QAction(MainWindow)
        self.actionCover_Types.setObjectName(_fromUtf8("actionCover_Types"))
        self.actionActual_Covers_Revenue = QtGui.QAction(MainWindow)
        self.actionActual_Covers_Revenue.setObjectName(_fromUtf8("actionActual_Covers_Revenue"))
        self.Budget_and_Actuals = QtGui.QAction(MainWindow)
        self.Budget_and_Actuals.setObjectName(_fromUtf8("Budget_and_Actuals"))
        self.actionPrint_Rota = QtGui.QAction(MainWindow)
        self.actionPrint_Rota.setObjectName(_fromUtf8("actionPrint_Rota"))
        self.actionPayroll_Variables = QtGui.QAction(MainWindow)
        self.actionPayroll_Variables.setObjectName(_fromUtf8("actionPayroll_Variables"))
        self.actionReporting_Tool = QtGui.QAction(MainWindow)
        self.actionReporting_Tool.setObjectName(_fromUtf8("actionReporting_Tool"))
        self.actionBudget_and_Actual = QtGui.QAction(MainWindow)
        self.actionBudget_and_Actual.setObjectName(_fromUtf8("actionBudget_and_Actual"))
        self.actionBudget_and_Actuals = QtGui.QAction(MainWindow)
        self.actionBudget_and_Actuals.setObjectName(_fromUtf8("actionBudget_and_Actuals"))
        self.menuReporting.addAction(self.actionReporting_Tool)
        self.menuFile.addAction(self.actionPrint_Rota)
        self.menuFunctions.addAction(self.actionEmployee)
        self.menuFunctions.addAction(self.actionPayroll_Variables)
        self.menuFunctions.addSeparator()
        self.menuFunctions.addAction(self.actionBudget_and_Actuals)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuFunctions.menuAction())
        self.menuBar.addAction(self.menuReporting.menuAction())
        self.menuBar.addAction(self.menuHolidays.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Rota System v2", None))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Name", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Monday", None))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Tuesday", None))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Wednesday", None))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Thursday", None))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Friday", None))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Saturday", None))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Sunday", None))
        item = self.coverHeaderTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Cover Totals", None))
        item = self.coverHeaderTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Mon Cov", None))
        item = self.coverHeaderTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Tue Cov", None))
        item = self.coverHeaderTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Wed Cov", None))
        item = self.coverHeaderTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Thur Cov", None))
        item = self.coverHeaderTable.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Fri Cov", None))
        item = self.coverHeaderTable.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "New Column", None))
        item = self.coverHeaderTable.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Sun Cov", None))
        self.delShiftBUT.setText(_translate("MainWindow", "Delete Shifts", None))
        self.label_3.setText(_translate("MainWindow", "Filter by Department", None))
        self.deleteWeekBUT.setText(_translate("MainWindow", "Delete Week", None))
        self.AddEmpBUT.setText(_translate("MainWindow", "Add Employee", None))
        self.AutoPopulate.setText(_translate("MainWindow", "Auto Populate", None))
        self.RemoveEmpBUT.setText(_translate("MainWindow", "Remove Employee", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.rotaTab), _translate("MainWindow", "Rota", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Weekly Wage Cost", None))
        self.predictedWagePerclbl.setText(_translate("MainWindow", "Pred. Wage %", None))
        self.predSalariedlbl.setText(_translate("MainWindow", "Pred. Salaried", None))
        self.predWagelbl.setText(_translate("MainWindow", "Pred. Wage", None))
        self.predHourlylbl.setText(_translate("MainWindow", "Pred. Hourly", None))
        self.predWageBox.setPrefix(_translate("MainWindow", "£", None))
        self.predSalariedBox.setPrefix(_translate("MainWindow", "£", None))
        self.predHourlyBox.setPrefix(_translate("MainWindow", "£", None))
        self.predWagePercBox.setSuffix(_translate("MainWindow", "%", None))
        self.groupBox.setTitle(_translate("MainWindow", "Weekly Paye Costs", None))
        self.predBonuslbl.setText(_translate("MainWindow", "Pred. Bonus", None))
        self.predPensionlbl.setText(_translate("MainWindow", "Pred. Pension", None))
        self.predBonusBox.setPrefix(_translate("MainWindow", "£", None))
        self.predPensionBox.setPrefix(_translate("MainWindow", "£", None))
        self.predNICBox.setPrefix(_translate("MainWindow", "£", None))
        self.predNIClbl.setText(_translate("MainWindow", "Pred. NIC", None))
        self.predSSPBox.setPrefix(_translate("MainWindow", "£", None))
        self.PredSSPlbl.setText(_translate("MainWindow", "Pred. SSP", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "Week to Date", None))
        self.wtdWageLbl.setText(_translate("MainWindow", "WTD Wage", None))
        self.wtdRevBox.setPrefix(_translate("MainWindow", "£", None))
        self.wtdWageBox.setPrefix(_translate("MainWindow", "£", None))
        self.wtdWagePerclbl.setText(_translate("MainWindow", "WTD Wage %", None))
        self.wtdWagePercBox.setSuffix(_translate("MainWindow", "%", None))
        self.wtdAVGSpendlbl.setText(_translate("MainWindow", "WTD Avg. £", None))
        self.wtdAvgSpendBox.setPrefix(_translate("MainWindow", "£", None))
        self.wtdRevlbl.setText(_translate("MainWindow", "WTD Rev.", None))
        self.groupBox_5.setTitle(_translate("MainWindow", "Month to Date", None))
        self.mtdWageBox.setPrefix(_translate("MainWindow", "£", None))
        self.mtdRevenue.setText(_translate("MainWindow", "MTD Rev.", None))
        self.mtdRevBox.setPrefix(_translate("MainWindow", "£", None))
        self.mtdWagePerc.setText(_translate("MainWindow", "MTD Wage %", None))
        self.mtdWagePercBox.setSuffix(_translate("MainWindow", "%", None))
        self.mtdAvgSpend.setText(_translate("MainWindow", "MTD Avg. £", None))
        self.mtdAvgSpendBox.setPrefix(_translate("MainWindow", "£", None))
        self.mtdWage.setText(_translate("MainWindow", "MTD Wage", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Weekly Revenue", None))
        self.predRevlbl.setText(_translate("MainWindow", "Pred. Rev.", None))
        self.predRevBox.setPrefix(_translate("MainWindow", "£", None))
        self.predAvgSpendBox.setPrefix(_translate("MainWindow", "£", None))
        self.predAVGSpendlbl.setText(_translate("MainWindow", "Pred. Avg. £", None))
        self.exAdminCheck.setText(_translate("MainWindow", "Exclude Admin in Calculation", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.wageTab), _translate("MainWindow", "Wage Cost", None))
        self.YTDCoverslbl.setText(_translate("MainWindow", "YTD Cover Total", None))
        self.MTDCoversLbl.setText(_translate("MainWindow", "MTD Covers Total", None))
        self.WeeklyCoversTotalLBL.setText(_translate("MainWindow", "Weekly Covers Total", None))
        self.coverUpdateBUT.setText(_translate("MainWindow", "Save & Refresh", None))
        item = self.predictedCoverTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "RevenueType", None))
        item = self.predictedCoverTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "MonAM", None))
        item = self.predictedCoverTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "MonPM", None))
        item = self.predictedCoverTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "TueAM ", None))
        item = self.predictedCoverTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "TuePM ", None))
        item = self.predictedCoverTable.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "WedAM", None))
        item = self.predictedCoverTable.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "WedPM", None))
        item = self.predictedCoverTable.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "ThurAM", None))
        item = self.predictedCoverTable.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "ThurPM", None))
        item = self.predictedCoverTable.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "FriAM   ", None))
        item = self.predictedCoverTable.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "FriPM   ", None))
        item = self.predictedCoverTable.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "SatAM  ", None))
        item = self.predictedCoverTable.horizontalHeaderItem(12)
        item.setText(_translate("MainWindow", "SatPM  ", None))
        item = self.predictedCoverTable.horizontalHeaderItem(13)
        item.setText(_translate("MainWindow", "SunAM ", None))
        item = self.predictedCoverTable.horizontalHeaderItem(14)
        item.setText(_translate("MainWindow", "SunPM ", None))
        self.addRevTypeBUT.setText(_translate("MainWindow", "Add Revenue Type", None))
        self.delRevenueTypeBUT.setText(_translate("MainWindow", "Del Revenue Type", None))
        self.monDateLBL.setText(_translate("MainWindow", "Mon", None))
        self.tueDateLBL.setText(_translate("MainWindow", "Tue", None))
        self.wedDateLBL.setText(_translate("MainWindow", "Wed", None))
        self.thurDateLBL.setText(_translate("MainWindow", "Thur", None))
        self.friDateLBL.setText(_translate("MainWindow", "Fri", None))
        self.satDateLBL.setText(_translate("MainWindow", "Sat", None))
        self.sunDateLBL.setText(_translate("MainWindow", "Sun", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.coverTab), _translate("MainWindow", "Covers", None))
        self.menuReporting.setTitle(_translate("MainWindow", "Reporting", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuHolidays.setTitle(_translate("MainWindow", "Holidays", None))
        self.menuFunctions.setTitle(_translate("MainWindow", "Data", None))
        self.actionEmployee.setText(_translate("MainWindow", "Employee Data", None))
        self.actionCover_forecast_by_type.setText(_translate("MainWindow", "Cover Forecast by Type", None))
        self.actionCover_Types.setText(_translate("MainWindow", "Cover Types", None))
        self.actionActual_Covers_Revenue.setText(_translate("MainWindow", "Actual Covers and Revenue", None))
        self.Budget_and_Actuals.setText(_translate("MainWindow", "Revenue Budget and Actuals", None))
        self.actionPrint_Rota.setText(_translate("MainWindow", "Print Rota", None))
        self.actionPayroll_Variables.setText(_translate("MainWindow", "Payroll Variables", None))
        self.actionReporting_Tool.setText(_translate("MainWindow", "Reporting Tool", None))
        self.actionBudget_and_Actual.setText(_translate("MainWindow", "Budget and Actual", None))
        self.actionBudget_and_Actuals.setText(_translate("MainWindow", "Budget and Actuals", None))

