# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ShiftPopUpWindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ShiftPopUpWindow(object):
    def setupUi(self, ShiftPopUpWindow):
        ShiftPopUpWindow.setObjectName(_fromUtf8("ShiftPopUpWindow"))
        ShiftPopUpWindow.resize(693, 435)
        self.CancelBUT = QtGui.QDialogButtonBox(ShiftPopUpWindow)
        self.CancelBUT.setGeometry(QtCore.QRect(502, 378, 86, 32))
        self.CancelBUT.setOrientation(QtCore.Qt.Horizontal)
        self.CancelBUT.setStandardButtons(QtGui.QDialogButtonBox.Cancel)
        self.CancelBUT.setObjectName(_fromUtf8("CancelBUT"))
        self.EmpNameBox = QtGui.QLineEdit(ShiftPopUpWindow)
        self.EmpNameBox.setGeometry(QtCore.QRect(20, 30, 241, 27))
        self.EmpNameBox.setReadOnly(True)
        self.EmpNameBox.setObjectName(_fromUtf8("EmpNameBox"))
        self.label = QtGui.QLabel(ShiftPopUpWindow)
        self.label.setGeometry(QtCore.QRect(20, 10, 181, 17))
        self.label.setObjectName(_fromUtf8("label"))
        self.ShiftDate = QtGui.QDateEdit(ShiftPopUpWindow)
        self.ShiftDate.setGeometry(QtCore.QRect(560, 30, 121, 27))
        self.ShiftDate.setReadOnly(True)
        self.ShiftDate.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.ShiftDate.setObjectName(_fromUtf8("ShiftDate"))
        self.label_2 = QtGui.QLabel(ShiftPopUpWindow)
        self.label_2.setGeometry(QtCore.QRect(560, 10, 101, 17))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.groupBox = QtGui.QGroupBox(ShiftPopUpWindow)
        self.groupBox.setGeometry(QtCore.QRect(20, 270, 201, 141))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(-1, 13, 41, 20))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(67, 13, 41, 20))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(131, 13, 41, 20))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.BrkAMBUT = QtGui.QPushButton(self.groupBox)
        self.BrkAMBUT.setGeometry(QtCore.QRect(126, 30, 61, 31))
        self.BrkAMBUT.setText(_fromUtf8(""))
        self.BrkAMBUT.setObjectName(_fromUtf8("BrkAMBUT"))
        self.StAMBUT = QtGui.QPushButton(self.groupBox)
        self.StAMBUT.setGeometry(QtCore.QRect(-1, 30, 61, 31))
        self.StAMBUT.setText(_fromUtf8(""))
        self.StAMBUT.setObjectName(_fromUtf8("StAMBUT"))
        self.FinAMBUT = QtGui.QPushButton(self.groupBox)
        self.FinAMBUT.setGeometry(QtCore.QRect(63, 30, 61, 31))
        self.FinAMBUT.setText(_fromUtf8(""))
        self.FinAMBUT.setObjectName(_fromUtf8("FinAMBUT"))
        self.AmShiftTypeCombo = QtGui.QComboBox(self.groupBox)
        self.AmShiftTypeCombo.setGeometry(QtCore.QRect(-1, 64, 121, 33))
        self.AmShiftTypeCombo.setObjectName(_fromUtf8("AmShiftTypeCombo"))
        self.AmShiftCLRBut = QtGui.QPushButton(self.groupBox)
        self.AmShiftCLRBut.setGeometry(QtCore.QRect(146, 70, 41, 27))
        self.AmShiftCLRBut.setObjectName(_fromUtf8("AmShiftCLRBut"))
        self.DepAMCombo = QtGui.QComboBox(self.groupBox)
        self.DepAMCombo.setGeometry(QtCore.QRect(0, 100, 121, 33))
        self.DepAMCombo.setObjectName(_fromUtf8("DepAMCombo"))
        self.groupBox_2 = QtGui.QGroupBox(ShiftPopUpWindow)
        self.groupBox_2.setGeometry(QtCore.QRect(260, 270, 191, 141))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(134, 13, 41, 20))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_8 = QtGui.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(70, 13, 41, 20))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_7 = QtGui.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(0, 13, 41, 20))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.BrkPMBUT = QtGui.QPushButton(self.groupBox_2)
        self.BrkPMBUT.setGeometry(QtCore.QRect(130, 30, 61, 31))
        self.BrkPMBUT.setText(_fromUtf8(""))
        self.BrkPMBUT.setObjectName(_fromUtf8("BrkPMBUT"))
        self.FinPMBUT = QtGui.QPushButton(self.groupBox_2)
        self.FinPMBUT.setGeometry(QtCore.QRect(66, 30, 61, 31))
        self.FinPMBUT.setText(_fromUtf8(""))
        self.FinPMBUT.setObjectName(_fromUtf8("FinPMBUT"))
        self.StPMBUT = QtGui.QPushButton(self.groupBox_2)
        self.StPMBUT.setGeometry(QtCore.QRect(0, 30, 61, 31))
        self.StPMBUT.setText(_fromUtf8(""))
        self.StPMBUT.setObjectName(_fromUtf8("StPMBUT"))
        self.PmShiftTypeCombo = QtGui.QComboBox(self.groupBox_2)
        self.PmShiftTypeCombo.setGeometry(QtCore.QRect(0, 64, 121, 33))
        self.PmShiftTypeCombo.setObjectName(_fromUtf8("PmShiftTypeCombo"))
        self.PmShiftCLRBut = QtGui.QPushButton(self.groupBox_2)
        self.PmShiftCLRBut.setGeometry(QtCore.QRect(150, 70, 41, 27))
        self.PmShiftCLRBut.setObjectName(_fromUtf8("PmShiftCLRBut"))
        self.DepPMCombo = QtGui.QComboBox(self.groupBox_2)
        self.DepPMCombo.setGeometry(QtCore.QRect(0, 100, 121, 33))
        self.DepPMCombo.setObjectName(_fromUtf8("DepPMCombo"))
        self.UdateBUT = QtGui.QPushButton(ShiftPopUpWindow)
        self.UdateBUT.setGeometry(QtCore.QRect(597, 380, 80, 27))
        self.UdateBUT.setObjectName(_fromUtf8("UdateBUT"))
        self.tabWidget = QtGui.QTabWidget(ShiftPopUpWindow)
        self.tabWidget.setGeometry(QtCore.QRect(20, 70, 661, 191))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.GenBut7 = QtGui.QPushButton(self.tab)
        self.GenBut7.setGeometry(QtCore.QRect(330, 100, 160, 50))
        self.GenBut7.setObjectName(_fromUtf8("GenBut7"))
        self.GenBut2 = QtGui.QPushButton(self.tab)
        self.GenBut2.setGeometry(QtCore.QRect(170, 30, 160, 50))
        self.GenBut2.setObjectName(_fromUtf8("GenBut2"))
        self.GenBut6 = QtGui.QPushButton(self.tab)
        self.GenBut6.setGeometry(QtCore.QRect(170, 100, 160, 50))
        self.GenBut6.setObjectName(_fromUtf8("GenBut6"))
        self.GenBut1 = QtGui.QPushButton(self.tab)
        self.GenBut1.setGeometry(QtCore.QRect(10, 30, 160, 50))
        self.GenBut1.setObjectName(_fromUtf8("GenBut1"))
        self.GenBut5 = QtGui.QPushButton(self.tab)
        self.GenBut5.setGeometry(QtCore.QRect(10, 100, 160, 50))
        self.GenBut5.setObjectName(_fromUtf8("GenBut5"))
        self.GenBut3 = QtGui.QPushButton(self.tab)
        self.GenBut3.setGeometry(QtCore.QRect(330, 30, 160, 50))
        self.GenBut3.setObjectName(_fromUtf8("GenBut3"))
        self.GenBut4 = QtGui.QPushButton(self.tab)
        self.GenBut4.setGeometry(QtCore.QRect(490, 30, 161, 50))
        self.GenBut4.setObjectName(_fromUtf8("GenBut4"))
        self.WedKit_3 = QtGui.QLabel(self.tab)
        self.WedKit_3.setGeometry(QtCore.QRect(332, 13, 71, 17))
        self.WedKit_3.setObjectName(_fromUtf8("WedKit_3"))
        self.friKit_3 = QtGui.QLabel(self.tab)
        self.friKit_3.setGeometry(QtCore.QRect(12, 84, 56, 17))
        self.friKit_3.setObjectName(_fromUtf8("friKit_3"))
        self.satKit_3 = QtGui.QLabel(self.tab)
        self.satKit_3.setGeometry(QtCore.QRect(172, 83, 56, 17))
        self.satKit_3.setObjectName(_fromUtf8("satKit_3"))
        self.TueKit_3 = QtGui.QLabel(self.tab)
        self.TueKit_3.setGeometry(QtCore.QRect(171, 13, 56, 17))
        self.TueKit_3.setObjectName(_fromUtf8("TueKit_3"))
        self.sunKit_3 = QtGui.QLabel(self.tab)
        self.sunKit_3.setGeometry(QtCore.QRect(332, 83, 56, 17))
        self.sunKit_3.setObjectName(_fromUtf8("sunKit_3"))
        self.monKit_3 = QtGui.QLabel(self.tab)
        self.monKit_3.setGeometry(QtCore.QRect(14, 13, 56, 17))
        self.monKit_3.setObjectName(_fromUtf8("monKit_3"))
        self.thurKit_3 = QtGui.QLabel(self.tab)
        self.thurKit_3.setGeometry(QtCore.QRect(491, 13, 56, 17))
        self.thurKit_3.setObjectName(_fromUtf8("thurKit_3"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.FOHBut2 = QtGui.QPushButton(self.tab_2)
        self.FOHBut2.setGeometry(QtCore.QRect(170, 30, 160, 50))
        self.FOHBut2.setObjectName(_fromUtf8("FOHBut2"))
        self.FOHBut7 = QtGui.QPushButton(self.tab_2)
        self.FOHBut7.setGeometry(QtCore.QRect(330, 100, 160, 50))
        self.FOHBut7.setObjectName(_fromUtf8("FOHBut7"))
        self.FOHBut6 = QtGui.QPushButton(self.tab_2)
        self.FOHBut6.setGeometry(QtCore.QRect(170, 100, 160, 50))
        self.FOHBut6.setObjectName(_fromUtf8("FOHBut6"))
        self.FOHBut1 = QtGui.QPushButton(self.tab_2)
        self.FOHBut1.setGeometry(QtCore.QRect(10, 30, 160, 50))
        self.FOHBut1.setObjectName(_fromUtf8("FOHBut1"))
        self.FOHBut5 = QtGui.QPushButton(self.tab_2)
        self.FOHBut5.setGeometry(QtCore.QRect(10, 100, 160, 50))
        self.FOHBut5.setObjectName(_fromUtf8("FOHBut5"))
        self.FOHBut3 = QtGui.QPushButton(self.tab_2)
        self.FOHBut3.setGeometry(QtCore.QRect(330, 30, 160, 50))
        self.FOHBut3.setObjectName(_fromUtf8("FOHBut3"))
        self.FOHBut4 = QtGui.QPushButton(self.tab_2)
        self.FOHBut4.setGeometry(QtCore.QRect(490, 30, 161, 50))
        self.FOHBut4.setObjectName(_fromUtf8("FOHBut4"))
        self.satKit_2 = QtGui.QLabel(self.tab_2)
        self.satKit_2.setGeometry(QtCore.QRect(172, 84, 56, 17))
        self.satKit_2.setObjectName(_fromUtf8("satKit_2"))
        self.sunKit_2 = QtGui.QLabel(self.tab_2)
        self.sunKit_2.setGeometry(QtCore.QRect(332, 84, 56, 17))
        self.sunKit_2.setObjectName(_fromUtf8("sunKit_2"))
        self.TueKit_2 = QtGui.QLabel(self.tab_2)
        self.TueKit_2.setGeometry(QtCore.QRect(171, 14, 56, 17))
        self.TueKit_2.setObjectName(_fromUtf8("TueKit_2"))
        self.monKit_2 = QtGui.QLabel(self.tab_2)
        self.monKit_2.setGeometry(QtCore.QRect(14, 14, 56, 17))
        self.monKit_2.setObjectName(_fromUtf8("monKit_2"))
        self.WedKit_2 = QtGui.QLabel(self.tab_2)
        self.WedKit_2.setGeometry(QtCore.QRect(332, 14, 71, 17))
        self.WedKit_2.setObjectName(_fromUtf8("WedKit_2"))
        self.thurKit_2 = QtGui.QLabel(self.tab_2)
        self.thurKit_2.setGeometry(QtCore.QRect(491, 14, 56, 17))
        self.thurKit_2.setObjectName(_fromUtf8("thurKit_2"))
        self.friKit_2 = QtGui.QLabel(self.tab_2)
        self.friKit_2.setGeometry(QtCore.QRect(12, 85, 56, 17))
        self.friKit_2.setObjectName(_fromUtf8("friKit_2"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.KitBut2 = QtGui.QPushButton(self.tab_3)
        self.KitBut2.setGeometry(QtCore.QRect(170, 30, 160, 50))
        self.KitBut2.setObjectName(_fromUtf8("KitBut2"))
        self.KitBut7 = QtGui.QPushButton(self.tab_3)
        self.KitBut7.setGeometry(QtCore.QRect(330, 100, 160, 50))
        self.KitBut7.setObjectName(_fromUtf8("KitBut7"))
        self.KitBut6 = QtGui.QPushButton(self.tab_3)
        self.KitBut6.setGeometry(QtCore.QRect(170, 100, 160, 50))
        self.KitBut6.setObjectName(_fromUtf8("KitBut6"))
        self.KitBut1 = QtGui.QPushButton(self.tab_3)
        self.KitBut1.setGeometry(QtCore.QRect(10, 30, 160, 50))
        self.KitBut1.setObjectName(_fromUtf8("KitBut1"))
        self.KitBut5 = QtGui.QPushButton(self.tab_3)
        self.KitBut5.setGeometry(QtCore.QRect(10, 100, 160, 50))
        self.KitBut5.setObjectName(_fromUtf8("KitBut5"))
        self.KitBut3 = QtGui.QPushButton(self.tab_3)
        self.KitBut3.setGeometry(QtCore.QRect(330, 30, 160, 50))
        self.KitBut3.setObjectName(_fromUtf8("KitBut3"))
        self.monKit = QtGui.QLabel(self.tab_3)
        self.monKit.setGeometry(QtCore.QRect(13, 14, 56, 17))
        self.monKit.setObjectName(_fromUtf8("monKit"))
        self.KitBut4 = QtGui.QPushButton(self.tab_3)
        self.KitBut4.setGeometry(QtCore.QRect(490, 30, 160, 50))
        self.KitBut4.setObjectName(_fromUtf8("KitBut4"))
        self.TueKit = QtGui.QLabel(self.tab_3)
        self.TueKit.setGeometry(QtCore.QRect(170, 14, 56, 17))
        self.TueKit.setObjectName(_fromUtf8("TueKit"))
        self.WedKit = QtGui.QLabel(self.tab_3)
        self.WedKit.setGeometry(QtCore.QRect(331, 14, 71, 17))
        self.WedKit.setObjectName(_fromUtf8("WedKit"))
        self.thurKit = QtGui.QLabel(self.tab_3)
        self.thurKit.setGeometry(QtCore.QRect(490, 14, 56, 17))
        self.thurKit.setObjectName(_fromUtf8("thurKit"))
        self.friKit = QtGui.QLabel(self.tab_3)
        self.friKit.setGeometry(QtCore.QRect(11, 85, 56, 17))
        self.friKit.setObjectName(_fromUtf8("friKit"))
        self.satKit = QtGui.QLabel(self.tab_3)
        self.satKit.setGeometry(QtCore.QRect(171, 84, 56, 17))
        self.satKit.setObjectName(_fromUtf8("satKit"))
        self.sunKit = QtGui.QLabel(self.tab_3)
        self.sunKit.setGeometry(QtCore.QRect(331, 84, 56, 17))
        self.sunKit.setObjectName(_fromUtf8("sunKit"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.AdminBut2 = QtGui.QPushButton(self.tab_4)
        self.AdminBut2.setGeometry(QtCore.QRect(170, 30, 160, 50))
        self.AdminBut2.setObjectName(_fromUtf8("AdminBut2"))
        self.AdminBut7 = QtGui.QPushButton(self.tab_4)
        self.AdminBut7.setGeometry(QtCore.QRect(330, 100, 160, 50))
        self.AdminBut7.setObjectName(_fromUtf8("AdminBut7"))
        self.AdminBut6 = QtGui.QPushButton(self.tab_4)
        self.AdminBut6.setGeometry(QtCore.QRect(170, 100, 160, 50))
        self.AdminBut6.setObjectName(_fromUtf8("AdminBut6"))
        self.AdminBut1 = QtGui.QPushButton(self.tab_4)
        self.AdminBut1.setGeometry(QtCore.QRect(10, 30, 160, 50))
        self.AdminBut1.setObjectName(_fromUtf8("AdminBut1"))
        self.AdminBut5 = QtGui.QPushButton(self.tab_4)
        self.AdminBut5.setGeometry(QtCore.QRect(10, 100, 160, 50))
        self.AdminBut5.setObjectName(_fromUtf8("AdminBut5"))
        self.AdminBut3 = QtGui.QPushButton(self.tab_4)
        self.AdminBut3.setGeometry(QtCore.QRect(330, 30, 160, 50))
        self.AdminBut3.setObjectName(_fromUtf8("AdminBut3"))
        self.label_16 = QtGui.QLabel(self.tab_4)
        self.label_16.setGeometry(QtCore.QRect(173, 84, 56, 17))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.label_17 = QtGui.QLabel(self.tab_4)
        self.label_17.setGeometry(QtCore.QRect(333, 84, 56, 17))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.label_18 = QtGui.QLabel(self.tab_4)
        self.label_18.setGeometry(QtCore.QRect(172, 14, 56, 17))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.label_19 = QtGui.QLabel(self.tab_4)
        self.label_19.setGeometry(QtCore.QRect(15, 14, 56, 17))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.label_20 = QtGui.QLabel(self.tab_4)
        self.label_20.setGeometry(QtCore.QRect(333, 14, 71, 17))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.label_21 = QtGui.QLabel(self.tab_4)
        self.label_21.setGeometry(QtCore.QRect(492, 14, 56, 17))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.label_22 = QtGui.QLabel(self.tab_4)
        self.label_22.setGeometry(QtCore.QRect(13, 85, 56, 17))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.AdminBut4 = QtGui.QPushButton(self.tab_4)
        self.AdminBut4.setGeometry(QtCore.QRect(490, 30, 161, 50))
        self.AdminBut4.setObjectName(_fromUtf8("AdminBut4"))
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.standardWeekBUT = QtGui.QPushButton(ShiftPopUpWindow)
        self.standardWeekBUT.setGeometry(QtCore.QRect(520, 300, 161, 31))
        self.standardWeekBUT.setObjectName(_fromUtf8("standardWeekBUT"))

        self.retranslateUi(ShiftPopUpWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.CancelBUT, QtCore.SIGNAL(_fromUtf8("accepted()")), ShiftPopUpWindow.accept)
        QtCore.QObject.connect(self.CancelBUT, QtCore.SIGNAL(_fromUtf8("rejected()")), ShiftPopUpWindow.reject)
        QtCore.QMetaObject.connectSlotsByName(ShiftPopUpWindow)

    def retranslateUi(self, ShiftPopUpWindow):
        ShiftPopUpWindow.setWindowTitle(_translate("ShiftPopUpWindow", "Shift Adjustment", None))
        self.label.setText(_translate("ShiftPopUpWindow", "Employee", None))
        self.ShiftDate.setDisplayFormat(_translate("ShiftPopUpWindow", "ddd dd MMM yyyy", None))
        self.label_2.setText(_translate("ShiftPopUpWindow", "Shift Date", None))
        self.groupBox.setTitle(_translate("ShiftPopUpWindow", "AM Shift", None))
        self.label_3.setText(_translate("ShiftPopUpWindow", "Start", None))
        self.label_4.setText(_translate("ShiftPopUpWindow", "Finish", None))
        self.label_5.setText(_translate("ShiftPopUpWindow", "Break", None))
        self.AmShiftCLRBut.setText(_translate("ShiftPopUpWindow", "CLR", None))
        self.groupBox_2.setTitle(_translate("ShiftPopUpWindow", "PM Shift", None))
        self.label_6.setText(_translate("ShiftPopUpWindow", "Break", None))
        self.label_8.setText(_translate("ShiftPopUpWindow", "Finish", None))
        self.label_7.setText(_translate("ShiftPopUpWindow", "Start", None))
        self.PmShiftCLRBut.setText(_translate("ShiftPopUpWindow", "CLR", None))
        self.UdateBUT.setText(_translate("ShiftPopUpWindow", "Update", None))
        self.GenBut7.setText(_translate("ShiftPopUpWindow", "Auto Shift", None))
        self.GenBut2.setText(_translate("ShiftPopUpWindow", "Auto Shift", None))
        self.GenBut6.setText(_translate("ShiftPopUpWindow", "Auto Shift", None))
        self.GenBut1.setText(_translate("ShiftPopUpWindow", "Auto Shift", None))
        self.GenBut5.setText(_translate("ShiftPopUpWindow", "Auto Shift", None))
        self.GenBut3.setText(_translate("ShiftPopUpWindow", "Auto Shift", None))
        self.GenBut4.setText(_translate("ShiftPopUpWindow", "Auto Shift", None))
        self.WedKit_3.setText(_translate("ShiftPopUpWindow", "Wednesday", None))
        self.friKit_3.setText(_translate("ShiftPopUpWindow", "Friday", None))
        self.satKit_3.setText(_translate("ShiftPopUpWindow", "Saturday", None))
        self.TueKit_3.setText(_translate("ShiftPopUpWindow", "Tuesday", None))
        self.sunKit_3.setText(_translate("ShiftPopUpWindow", "Sunday", None))
        self.monKit_3.setText(_translate("ShiftPopUpWindow", "Monday", None))
        self.thurKit_3.setText(_translate("ShiftPopUpWindow", "Thursday", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("ShiftPopUpWindow", "General ", None))
        self.FOHBut2.setText(_translate("ShiftPopUpWindow", "Auto Shift", None))
        self.FOHBut7.setText(_translate("ShiftPopUpWindow", "Auto Shift", None))
        self.FOHBut6.setText(_translate("ShiftPopUpWindow", "Auto Shift", None))
        self.FOHBut1.setText(_translate("ShiftPopUpWindow", "Auto Shift", None))
        self.FOHBut5.setText(_translate("ShiftPopUpWindow", "Auto Shift", None))
        self.FOHBut3.setText(_translate("ShiftPopUpWindow", "Auto Shift", None))
        self.FOHBut4.setText(_translate("ShiftPopUpWindow", "Auto Shift", None))
        self.satKit_2.setText(_translate("ShiftPopUpWindow", "Saturday", None))
        self.sunKit_2.setText(_translate("ShiftPopUpWindow", "Sunday", None))
        self.TueKit_2.setText(_translate("ShiftPopUpWindow", "Tuesday", None))
        self.monKit_2.setText(_translate("ShiftPopUpWindow", "Monday", None))
        self.WedKit_2.setText(_translate("ShiftPopUpWindow", "Wednesday", None))
        self.thurKit_2.setText(_translate("ShiftPopUpWindow", "Thursday", None))
        self.friKit_2.setText(_translate("ShiftPopUpWindow", "Friday", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("ShiftPopUpWindow", "FOH", None))
        self.KitBut2.setText(_translate("ShiftPopUpWindow", "Auto Shift", None))
        self.KitBut7.setText(_translate("ShiftPopUpWindow", "Auto Shift", None))
        self.KitBut6.setText(_translate("ShiftPopUpWindow", "Auto Shift", None))
        self.KitBut1.setText(_translate("ShiftPopUpWindow", "Auto Shift", None))
        self.KitBut5.setText(_translate("ShiftPopUpWindow", "Auto Shift", None))
        self.KitBut3.setText(_translate("ShiftPopUpWindow", "Auto Shift", None))
        self.monKit.setText(_translate("ShiftPopUpWindow", "Monday", None))
        self.KitBut4.setText(_translate("ShiftPopUpWindow", "Auto Shift", None))
        self.TueKit.setText(_translate("ShiftPopUpWindow", "Tuesday", None))
        self.WedKit.setText(_translate("ShiftPopUpWindow", "Wednesday", None))
        self.thurKit.setText(_translate("ShiftPopUpWindow", "Thursday", None))
        self.friKit.setText(_translate("ShiftPopUpWindow", "Friday", None))
        self.satKit.setText(_translate("ShiftPopUpWindow", "Saturday", None))
        self.sunKit.setText(_translate("ShiftPopUpWindow", "Sunday", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("ShiftPopUpWindow", "Kitchen", None))
        self.AdminBut2.setText(_translate("ShiftPopUpWindow", "Auto Shift", None))
        self.AdminBut7.setText(_translate("ShiftPopUpWindow", "Auto Shift", None))
        self.AdminBut6.setText(_translate("ShiftPopUpWindow", "Auto Shift", None))
        self.AdminBut1.setText(_translate("ShiftPopUpWindow", "Auto Shift", None))
        self.AdminBut5.setText(_translate("ShiftPopUpWindow", "Auto Shift", None))
        self.AdminBut3.setText(_translate("ShiftPopUpWindow", "Auto Shift", None))
        self.label_16.setText(_translate("ShiftPopUpWindow", "Saturday", None))
        self.label_17.setText(_translate("ShiftPopUpWindow", "Sunday", None))
        self.label_18.setText(_translate("ShiftPopUpWindow", "Tuesday", None))
        self.label_19.setText(_translate("ShiftPopUpWindow", "Monday", None))
        self.label_20.setText(_translate("ShiftPopUpWindow", "Wednesday", None))
        self.label_21.setText(_translate("ShiftPopUpWindow", "Thursday", None))
        self.label_22.setText(_translate("ShiftPopUpWindow", "Friday", None))
        self.AdminBut4.setText(_translate("ShiftPopUpWindow", "Auto Shift", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("ShiftPopUpWindow", "Admin", None))
        self.standardWeekBUT.setText(_translate("ShiftPopUpWindow", "Populate Standard Week", None))

